// ══════════════════════════════════════
// AgentLimb i18n — 12 languages
// ══════════════════════════════════════

export const LANGS = [
  { code: 'en', name: 'English',    flag: '🇺🇸' },
  { code: 'zh', name: '简体中文',    flag: '🇨🇳' },
  { code: 'ja', name: '日本語',     flag: '🇯🇵' },
  { code: 'ko', name: '한국어',     flag: '🇰🇷' },
  { code: 'es', name: 'Español',    flag: '🇪🇸' },
  { code: 'fr', name: 'Français',   flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch',    flag: '🇩🇪' },
  { code: 'pt', name: 'Português',  flag: '🇧🇷' },
  { code: 'ru', name: 'Русский',    flag: '🇷🇺' },
  { code: 'ar', name: 'العربية',    flag: '🇸🇦' },
  { code: 'it', name: 'Italiano',   flag: '🇮🇹' },
  { code: 'hi', name: 'हिन्दी',      flag: '🇮🇳' },
];

const T = {
  // ── Nav ──
  'nav.features':     { en:'Features', zh:'特色功能', ja:'特徴', ko:'기능', es:'Funciones', fr:'Fonctionnalités', de:'Funktionen', pt:'Recursos', ru:'Функции', ar:'الميزات', it:'Funzionalità', hi:'विशेषताएं' },
  'nav.tutorials':    { en:'Tutorials', zh:'教程', ja:'チュートリアル', ko:'튜토리얼', es:'Tutoriales', fr:'Tutoriels', de:'Tutorials', pt:'Tutoriais', ru:'Руководства', ar:'الدروس', it:'Tutorial', hi:'ट्यूटोरियल' },
  'nav.tools':        { en:'AI Tools', zh:'AI 工具', ja:'AIツール', ko:'AI 도구', es:'Herramientas IA', fr:'Outils IA', de:'KI-Tools', pt:'Ferramentas IA', ru:'ИИ-инструменты', ar:'أدوات الذكاء', it:'Strumenti IA', hi:'AI उपकरण' },
  'nav.news':         { en:'News', zh:'新闻', ja:'ニュース', ko:'뉴스', es:'Noticias', fr:'Actualités', de:'Nachrichten', pt:'Notícias', ru:'Новости', ar:'الأخبار', it:'Notizie', hi:'समाचार' },

  // ── Hero ──
  'hero.line1':       { en:'Stop Watching Your AI', zh:'别再看着你的 AI', ja:'AIが同じタスクを', ko:'AI가 같은 작업을', es:'Deja de ver a tu IA', fr:'Arrête de voir ton IA', de:'Hör auf zuzusehen, wie deine KI', pt:'Pare de ver sua IA', ru:'Перестань наблюдать, как твой ИИ', ar:'أوقف مشاهدة ذكاءك الاصطناعي', it:'Smetti di guardare la tua IA', hi:'अपने AI को देखना बंद करो' },
  'hero.line2':       { en:'Relearn the Same Task', zh:'重新学习同一件事', ja:'学び直すのをやめる', ko:'같은 작업을 다시 배우는 것을', es:'Reaprendiendo la Misma Tarea', fr:'Réapprendre la Même Tâche', de:'Die Gleiche Aufgabe Neu Lernt', pt:'Reaprendendo a Mesma Tarefa', ru:'Снова Учится Тому Же', ar:'يُعيد تعلم نفس المهمة', it:'Riapprende lo Stesso Compito', hi:'वही काम दोबारा सीखता रहे' },
  'hero.sub':         { en:'Record once. Replay forever. 90% fewer tokens.', zh:'记录一次。永久回放。减少 90% token。', ja:'一度記録。永久リプレイ。トークン90%削減。', ko:'한 번 기록. 영원히 재생. 토큰 90% 절감.', es:'Graba una vez. Reproduce siempre. 90% menos tokens.', fr:'Enregistre une fois. Rejoue pour toujours. 90% moins de tokens.', de:'Einmal aufnehmen. Für immer abspielen. 90% weniger Tokens.', pt:'Grave uma vez. Reproduza para sempre. 90% menos tokens.', ru:'Запись один раз. Воспроизведение навсегда. На 90% меньше токенов.', ar:'سجّل مرة. أعد التشغيل للأبد. 90% أقل من الرموز.', it:'Registra una volta. Riproduci per sempre. 90% meno token.', hi:'एक बार रिकॉर्ड करें। हमेशा रीप्ले करें। 90% कम टोकन।' },
  'hero.desc':        { en:'Works with Claude Code, Cursor, Codex, Windsurf, or any AI that can run commands — no setup, no API keys, your existing Chrome sessions.', zh:'兼容 Claude Code、Cursor、Codex、Windsurf，以及任何能运行命令的 AI 工具——无需配置，无需 API Key，直接使用你的 Chrome 登录态。', ja:'Claude Code、Cursor、Codex、Windsurf、またはコマンドを実行できるAIならどれでも——設定不要、APIキー不要、既存のChromeセッションをそのまま使用。', ko:'Claude Code, Cursor, Codex, Windsurf 또는 명령을 실행할 수 있는 모든 AI 호환——설정 불필요, API 키 불필요, 기존 Chrome 세션 그대로.', es:'Compatible con Claude Code, Cursor, Codex, Windsurf, o cualquier IA que ejecute comandos — sin configuración, sin API keys, tus sesiones Chrome existentes.', fr:'Fonctionne avec Claude Code, Cursor, Codex, Windsurf, ou tout IA pouvant exécuter des commandes — sans configuration, sans clés API, vos sessions Chrome existantes.', de:'Funktioniert mit Claude Code, Cursor, Codex, Windsurf oder jedem KI-Tool, das Befehle ausführen kann — keine Einrichtung, keine API-Schlüssel, deine bestehenden Chrome-Sitzungen.', pt:'Funciona com Claude Code, Cursor, Codex, Windsurf, ou qualquer IA que execute comandos — sem configuração, sem API keys, suas sessões Chrome existentes.', ru:'Работает с Claude Code, Cursor, Codex, Windsurf или любым ИИ, способным выполнять команды — без настройки, без API-ключей, ваши существующие сессии Chrome.', ar:'يعمل مع Claude Code وCursor وCodex وWindsurf وأي ذكاء اصطناعي يمكنه تشغيل الأوامر — بدون إعداد، بدون مفاتيح API، جلسات Chrome الموجودة.', it:'Funziona con Claude Code, Cursor, Codex, Windsurf, o qualsiasi IA che esegue comandi — nessuna configurazione, nessuna API key, le tue sessioni Chrome esistenti.', hi:'Claude Code, Cursor, Codex, Windsurf, या कोई भी AI जो कमांड चला सके——कोई सेटअप नहीं, कोई API Key नहीं, आपके मौजूदा Chrome सत्र।' },
  'hero.badge':       { en:'Open-source alternative to CoWork', zh:'CoWork 的开源替代方案', ja:'CoWorkのオープンソース代替', ko:'CoWork의 오픈소스 대안', es:'La alternativa open-source a CoWork', fr:'L\'alternative open-source à CoWork', de:'Die Open-Source-Alternative zu CoWork', pt:'A alternativa open-source ao CoWork', ru:'Альтернатива CoWork с открытым кодом', ar:'البديل مفتوح المصدر لـ CoWork', it:'L\'alternativa open-source a CoWork', hi:'CoWork का ओपन-सोर्स विकल्प' },
  'hero.chrome':      { en:'Add to Chrome', zh:'添加到 Chrome', ja:'Chromeに追加', ko:'Chrome에 추가', es:'Añadir a Chrome', fr:'Ajouter à Chrome', de:'Zu Chrome hinzufügen', pt:'Adicionar ao Chrome', ru:'Добавить в Chrome', ar:'أضف إلى Chrome', it:'Aggiungi a Chrome', hi:'Chrome में जोड़ें' },
  'hero.github':      { en:'Star on GitHub ⭐️', zh:'在 GitHub 给我们加星 ⭐️', ja:'GitHubでスターを ⭐️', ko:'GitHub에서 스타 주기 ⭐️', es:'Estrella en GitHub ⭐️', fr:'Étoile sur GitHub ⭐️', de:'Stern auf GitHub ⭐️', pt:'Estrela no GitHub ⭐️', ru:'Звезда на GitHub ⭐️', ar:'نجمة على GitHub ⭐️', it:'Stella su GitHub ⭐️', hi:'GitHub पर स्टार दें ⭐️' },
  'hero.installHint': { en:'Download zip · Enable Developer Mode in chrome://extensions · Unzip · Load unpacked', zh:'下载压缩包 · 在 chrome://extensions 开启开发者模式 · 解压 · 加载已解压的文件夹', ja:'zipをダウンロード · chrome://extensions で開発者モードを有効化 · 解凍 · フォルダを読み込む', ko:'zip 다운로드 · chrome://extensions에서 개발자 모드 활성화 · 압축 해제 · 폴더 로드', es:'Descarga zip · Activa el Modo Desarrollador en chrome://extensions · Descomprime · Carga la carpeta', fr:'Télécharge zip · Active le Mode Développeur dans chrome://extensions · Décompresse · Charge le dossier', de:'zip herunterladen · Entwicklermodus in chrome://extensions aktivieren · Entpacken · Ordner laden', pt:'Baixe o zip · Ative o Modo Desenvolvedor em chrome://extensions · Descompacte · Carregue a pasta', ru:'Скачайте zip · Включите режим разработчика в chrome://extensions · Распакуйте · Загрузите папку', ar:'حمّل الملف المضغوط · فعّل وضع المطور في chrome://extensions · فك الضغط · حمّل المجلد', it:'Scarica zip · Attiva Modalità Sviluppatore in chrome://extensions · Decomprimi · Carica cartella', hi:'zip डाउनलोड करें · chrome://extensions में Developer Mode चालू करें · अनज़िप करें · फ़ोल्डर लोड करें' },

  // ── Features ──
  'feat.label':       { en:'Why AgentLimb', zh:'为什么选择 AgentLimb', ja:'AgentLimbを選ぶ理由', ko:'왜 AgentLimb인가', es:'Por qué AgentLimb', fr:'Pourquoi AgentLimb', de:'Warum AgentLimb', pt:'Por que AgentLimb', ru:'Почему AgentLimb', ar:'لماذا AgentLimb', it:'Perché AgentLimb', hi:'AgentLimb क्यों' },
  'feat.title':       { en:'Your AI is wasting tokens doing the same thing every day.', zh:'你的 AI 每天都在用 token 重复做同一件事。', ja:'あなたのAIは毎日同じことをしてトークンを無駄にしています。', ko:'당신의 AI는 매일 같은 일을 하며 토큰을 낭비하고 있습니다.', es:'Tu IA desperdicia tokens haciendo lo mismo cada día.', fr:'Votre IA gaspille des tokens à faire la même chose chaque jour.', de:'Deine KI verschwendet täglich Tokens, indem sie dasselbe tut.', pt:'Sua IA desperdiça tokens fazendo a mesma coisa todos os dias.', ru:'Ваш ИИ тратит токены на одно и то же каждый день.', ar:'ذكاؤك الاصطناعي يهدر الرموز بفعل نفس الشيء كل يوم.', it:'La tua IA spreca token facendo la stessa cosa ogni giorno.', hi:'आपका AI हर दिन वही काम करके टोकन बर्बाद कर रहा है।' },
  'feat.desc':        { en:'Every task, it re-explores from scratch. AgentLimb fixes that.', zh:'每次任务，它都从零开始重新探索。AgentLimb 解决这个问题。', ja:'毎回、ゼロから再探索します。AgentLimbがそれを解決します。', ko:'매번 처음부터 다시 탐색합니다. AgentLimb가 해결합니다.', es:'Cada tarea, re-explora desde cero. AgentLimb lo soluciona.', fr:'Chaque tâche, il ré-explore depuis zéro. AgentLimb règle ça.', de:'Jede Aufgabe erkundet es von Grund auf neu. AgentLimb behebt das.', pt:'Cada tarefa, re-explora do zero. AgentLimb resolve isso.', ru:'Каждую задачу исследует заново. AgentLimb это исправляет.', ar:'كل مهمة، يستكشفها من البداية. AgentLimb يحل ذلك.', it:'Ogni task, ri-esplora da zero. AgentLimb risolve questo.', hi:'हर काम में शुरू से एक्सप्लोर करता है। AgentLimb इसे ठीक करता है।' },

  'feat.1.title':     { en:'90% Fewer Tokens', zh:'减少 90% Token 消耗', ja:'トークン90%削減', ko:'토큰 90% 절감', es:'90% Menos Tokens', fr:'90% Moins de Tokens', de:'90% Weniger Tokens', pt:'90% Menos Tokens', ru:'На 90% Меньше Токенов', ar:'90% أقل من الرموز', it:'90% Meno Token', hi:'90% कम टोकन' },
  'feat.1.desc':      { en:'AI explores a task once and saves the route as a "muscle." Every replay after that skips the exploration entirely — same result, a fraction of the cost.', zh:'AI 探索一次任务，将路径存为「肌肉」。此后每次回放都跳过探索——结果一样，成本只有零头。', ja:'AIがタスクを一度探索し、ルートを「マッスル」として保存。それ以降のリプレイは探索をすべてスキップ——同じ結果、わずかなコスト。', ko:'AI가 작업을 한 번 탐색하고 경로를 \'근육\'으로 저장. 이후 모든 재생은 탐색을 완전히 건너뜁니다 — 같은 결과, 비용은 일부.', es:'La IA explora una tarea una vez y guarda la ruta como un "músculo". Cada reproducción posterior omite la exploración — mismo resultado, una fracción del costo.', fr:'L\'IA explore une tâche une fois et sauvegarde la route comme un "muscle". Chaque replay omite l\'exploration — même résultat, une fraction du coût.', de:'Die KI erkundet eine Aufgabe einmal und speichert die Route als "Muskel". Jeder spätere Replay überspringt die Erkundung — gleiches Ergebnis, ein Bruchteil der Kosten.', pt:'A IA explora uma tarefa uma vez e salva a rota como um "músculo". Cada replay depois pula a exploração — mesmo resultado, fração do custo.', ru:'ИИ исследует задачу один раз и сохраняет маршрут как «мускул». Каждый последующий запуск пропускает исследование — тот же результат, часть стоимости.', ar:'يستكشف الذكاء الاصطناعي مهمة مرة واحدة ويحفظ المسار كـ"عضلة". كل إعادة تشغيل تتخطى الاستكشاف — نفس النتيجة، جزء من التكلفة.', it:'L\'IA esplora un task una volta e salva il percorso come "muscolo". Ogni replay successivo salta l\'esplorazione — stesso risultato, una frazione del costo.', hi:'AI एक बार टास्क एक्सप्लोर करके रूट को \'मसल\' के रूप में सेव करता है। उसके बाद हर रीप्ले एक्सप्लोरेशन छोड़ देता है——वही नतीजा, बहुत कम लागत।' },
  'feat.2.title':     { en:'Any AI Tool. Zero Setup.', zh:'任何 AI 工具，零配置', ja:'どのAIツールでも。設定ゼロ。', ko:'모든 AI 도구. 설정 제로.', es:'Cualquier IA. Sin Configuración.', fr:'N\'importe quel IA. Zéro Configuration.', de:'Jedes KI-Tool. Null Einrichtung.', pt:'Qualquer IA. Zero Configuração.', ru:'Любой ИИ-инструмент. Ноль настроек.', ar:'أي أداة ذكاء اصطناعي. بدون إعداد.', it:'Qualsiasi IA. Zero Configurazione.', hi:'कोई भी AI टूल। ज़ीरो सेटअप।' },
  'feat.2.desc':      { en:'Claude Code, Cursor, Codex, Trae, Windsurf — paste one prompt and your AI auto-configures in seconds. No config files, no API keys.', zh:'Claude Code、Cursor、Codex、Trae、Windsurf——粘贴一个提示词，AI 秒完成自配置。无配置文件，无 API Key。', ja:'Claude Code、Cursor、Codex、Trae、Windsurf——プロンプトを1つ貼り付けると、AIが数秒で自動設定。設定ファイルなし、APIキーなし。', ko:'Claude Code, Cursor, Codex, Trae, Windsurf——프롬프트 하나를 붙여넣으면 AI가 몇 초 만에 자동 구성. 설정 파일 없음, API 키 없음.', es:'Claude Code, Cursor, Codex, Trae, Windsurf — pega un prompt y tu IA se auto-configura en segundos. Sin archivos de configuración, sin API keys.', fr:'Claude Code, Cursor, Codex, Trae, Windsurf — collez un prompt et votre IA se configure en quelques secondes. Pas de fichiers de configuration, pas de clés API.', de:'Claude Code, Cursor, Codex, Trae, Windsurf — einen Prompt einfügen und deine KI konfiguriert sich in Sekunden. Keine Konfigurationsdateien, keine API-Schlüssel.', pt:'Claude Code, Cursor, Codex, Trae, Windsurf — cole um prompt e sua IA se auto-configura em segundos. Sem arquivos de configuração, sem API keys.', ru:'Claude Code, Cursor, Codex, Trae, Windsurf — вставьте один промпт и ваш ИИ настраивается за секунды. Без файлов конфигурации, без API-ключей.', ar:'Claude Code وCursor وCodex وTrae وWindsurf — الصق موجهًا واحدًا ويتم إعداد ذكاؤك الاصطناعي تلقائيًا في ثوانٍ. بدون ملفات إعداد، بدون مفاتيح API.', it:'Claude Code, Cursor, Codex, Trae, Windsurf — incolla un prompt e la tua IA si auto-configura in secondi. Nessun file di configurazione, nessuna API key.', hi:'Claude Code, Cursor, Codex, Trae, Windsurf——एक प्रॉम्प्ट पेस्ट करें और आपका AI सेकंडों में ऑटो-कॉन्फ़िगर हो जाता है। कोई कॉन्फ़िग फ़ाइल नहीं, कोई API Key नहीं।' },
  'feat.3.title':     { en:'Your Real Browser. Your Real Sessions.', zh:'你的真实浏览器，你的真实登录态', ja:'あなたの実際のブラウザ。あなたの実際のセッション。', ko:'실제 브라우저. 실제 세션.', es:'Tu Navegador Real. Tus Sesiones Reales.', fr:'Votre Vrai Navigateur. Vos Vraies Sessions.', de:'Dein Echter Browser. Deine Echten Sitzungen.', pt:'Seu Navegador Real. Suas Sessões Reais.', ru:'Ваш Настоящий Браузер. Ваши Настоящие Сессии.', ar:'متصفحك الحقيقي. جلساتك الحقيقية.', it:'Il Tuo Vero Browser. Le Tue Vere Sessioni.', hi:'आपका असली ब्राउज़र। आपके असली सत्र।' },
  'feat.3.desc':      { en:'No headless Chrome. No re-login. No separate instances. Your cookies, logins, and extensions — all intact. If you can see it, your AI can use it.', zh:'无无头 Chrome，无需重新登录，无独立实例。你的 Cookie、登录态和扩展——全部保留。能看到的，AI 都能用。', ja:'ヘッドレスChromeなし。再ログインなし。別インスタンスなし。Cookie、ログイン、拡張機能——すべてそのまま。見えるものはAIが使える。', ko:'헤드리스 Chrome 없음. 재로그인 없음. 별도 인스턴스 없음. 쿠키, 로그인, 확장 프로그램——모두 그대로. 볼 수 있으면 AI가 사용합니다.', es:'Sin Chrome headless. Sin re-login. Sin instancias separadas. Tus cookies, logins y extensiones — todo intacto. Si puedes verlo, tu IA puede usarlo.', fr:'Pas de Chrome headless. Pas de reconnexion. Pas d\'instances séparées. Vos cookies, logins et extensions — tous intacts. Si vous le voyez, votre IA peut l\'utiliser.', de:'Kein Headless-Chrome. Kein erneutes Einloggen. Keine separaten Instanzen. Deine Cookies, Logins und Erweiterungen — alles intakt. Was du siehst, kann deine KI nutzen.', pt:'Sem Chrome headless. Sem re-login. Sem instâncias separadas. Seus cookies, logins e extensões — tudo intacto. Se você pode ver, sua IA pode usar.', ru:'Без headless Chrome. Без повторного входа. Без отдельных экземпляров. Ваши куки, логины и расширения — всё нетронуто. Если вы это видите, ваш ИИ может это использовать.', ar:'بدون Chrome بلا واجهة. بدون إعادة تسجيل دخول. بدون نسخ منفصلة. ملفات تعريف الارتباط وعمليات تسجيل الدخول والإضافات — كلها سليمة. إذا كنت تراه، يمكن لذكاؤك الاصطناعي استخدامه.', it:'Nessun Chrome headless. Nessun re-login. Nessuna istanza separata. Cookie, login ed estensioni — tutto intatto. Se lo vedi, la tua IA può usarlo.', hi:'कोई हेडलेस Chrome नहीं। दोबारा लॉगिन नहीं। अलग इंस्टेंस नहीं। आपके कुकीज़, लॉगिन और एक्सटेंशन——सब बरकरार। जो आप देख सकते हैं, AI उसे उपयोग कर सकता है।' },
  'feat.4.title':     { en:'100% Local & Private', zh:'100% 本地 & 隐私', ja:'100% ローカル & プライベート', ko:'100% 로컬 & 비공개', es:'100% Local y Privado', fr:'100% Local et Privé', de:'100% Lokal & Privat', pt:'100% Local e Privado', ru:'100% Локально и Приватно', ar:'100% محلي وخاص', it:'100% Locale e Privato', hi:'100% लोकल और प्राइवेट' },
  'feat.4.desc':      { en:'Everything runs on localhost. No analytics, no tracking, no cloud. Your browsing data never leaves your machine.', zh:'全部运行在本机。无分析，无追踪，无云端。你的浏览数据从不离开你的设备。', ja:'すべてlocalhostで実行。分析なし、追跡なし、クラウドなし。閲覧データはデバイスから出ない。', ko:'모든 것이 localhost에서 실행됩니다. 분석 없음, 추적 없음, 클라우드 없음. 브라우징 데이터는 기기를 절대 떠나지 않습니다.', es:'Todo corre en localhost. Sin analytics, sin tracking, sin nube. Tus datos nunca salen de tu máquina.', fr:'Tout tourne sur localhost. Pas d\'analytics, pas de tracking, pas de cloud. Vos données ne quittent jamais votre machine.', de:'Alles läuft auf localhost. Keine Analytik, kein Tracking, keine Cloud. Deine Daten verlassen nie deinen Rechner.', pt:'Tudo roda no localhost. Sem analytics, sem tracking, sem nuvem. Seus dados nunca saem da sua máquina.', ru:'Всё работает на localhost. Без аналитики, без отслеживания, без облака. Ваши данные никогда не покидают машину.', ar:'كل شيء يعمل على localhost. بدون تحليلات، بدون تتبع، بدون سحابة. بياناتك لا تغادر جهازك أبدًا.', it:'Tutto gira su localhost. Nessun analytics, nessun tracking, nessun cloud. I tuoi dati non lasciano mai la tua macchina.', hi:'सब कुछ localhost पर चलता है। कोई एनालिटिक्स नहीं, ट्रैकिंग नहीं, क्लाउड नहीं। आपका डेटा कभी आपकी मशीन नहीं छोड़ता।' },
  'feat.5.title':     { en:'Any Website, Any Platform', zh:'任何网站，任何平台', ja:'どんなサイトでも、どのプラットフォームでも', ko:'모든 웹사이트, 모든 플랫폼', es:'Cualquier Sitio, Cualquier Plataforma', fr:'N\'importe Quel Site, N\'importe Quelle Plateforme', de:'Jede Website, Jede Plattform', pt:'Qualquer Site, Qualquer Plataforma', ru:'Любой сайт, любая платформа', ar:'أي موقع، أي منصة', it:'Qualsiasi Sito, Qualsiasi Piattaforma', hi:'कोई भी वेबसाइट, कोई भी प्लेटफॉर्म' },
  'feat.5.desc':      { en:'Social media, SaaS dashboards, internal tools, email — anywhere your Chrome can go, your AI can operate.', zh:'社交媒体、SaaS 后台、内部工具、邮件——Chrome 能去的地方，AI 都能操作。', ja:'SNS、SaaSダッシュボード、社内ツール、メール——Chromeが行けるところならAIも操作できる。', ko:'소셜 미디어, SaaS 대시보드, 내부 도구, 이메일——Chrome이 갈 수 있는 곳이면 AI도 조작할 수 있습니다.', es:'Redes sociales, dashboards SaaS, herramientas internas, email — donde tu Chrome vaya, tu IA puede operar.', fr:'Réseaux sociaux, tableaux SaaS, outils internes, email — partout où Chrome peut aller, votre IA peut opérer.', de:'Social Media, SaaS-Dashboards, interne Tools, E-Mail — überall wo Chrome hingehen kann, kann deine KI arbeiten.', pt:'Redes sociais, dashboards SaaS, ferramentas internas, email — onde seu Chrome for, sua IA pode operar.', ru:'Соцсети, панели SaaS, внутренние инструменты, почта — куда Chrome может пойти, ваш ИИ может работать.', ar:'وسائل التواصل الاجتماعي، لوحات SaaS، الأدوات الداخلية، البريد الإلكتروني — أينما يذهب Chrome، يمكن لذكاؤك الاصطناعي العمل.', it:'Social media, dashboard SaaS, strumenti interni, email — ovunque Chrome possa andare, la tua IA può operare.', hi:'सोशल मीडिया, SaaS डैशबोर्ड, इंटरनल टूल्स, ईमेल——Chrome जहाँ जा सकता है, AI वहाँ काम कर सकता है।' },
  'feat.6.title':     { en:'Explicit Task Lifecycle', zh:'显式任务生命周期', ja:'明示的タスクライフサイクル', ko:'명시적 작업 수명 주기', es:'Ciclo de Vida Explícito', fr:'Cycle de Vie Explicite', de:'Expliziter Aufgabenlebenszyklus', pt:'Ciclo de Vida Explícito', ru:'Явный жизненный цикл задачи', ar:'دورة حياة المهمة الصريحة', it:'Ciclo di Vita Esplicito', hi:'स्पष्ट टास्क लाइफसाइकल' },
  'feat.6.desc':      { en:'Silence no longer equals success. AI declares task_plan → task_step_done → task_complete / task_fail. Timeouts and bridge drops show as real failures — the side panel renders live step progress.', zh:'沉默不再等于成功。AI 显式声明 task_plan → task_step_done → task_complete / task_fail。超时和断连作为真实失败显示——侧边面板实时渲染步骤进度。', ja:'沈黙はもはや成功を意味しない。AIがtask_plan→task_step_done→task_complete/task_failを明示宣言。タイムアウトや切断はリアルな失敗として表示——サイドパネルがステップをリアルタイムで描画。', ko:'침묵은 더 이상 성공이 아닙니다. AI가 task_plan → task_step_done → task_complete / task_fail을 명시적으로 선언. 타임아웃과 연결 끊김도 실제 실패로 표시——사이드 패널이 라이브 단계 진행을 렌더링.', es:'El silencio ya no equivale a éxito. La IA declara task_plan → task_step_done → task_complete / task_fail. Los timeouts y cortes del bridge se muestran como fallos reales — el panel lateral renderiza el progreso en vivo.', fr:'Le silence n\'est plus un succès. L\'IA déclare task_plan → task_step_done → task_complete / task_fail. Les timeouts et coupures s\'affichent comme de vrais échecs — le panel latéral affiche la progression en direct.', de:'Schweigen bedeutet kein Erfolg mehr. Die KI erklärt task_plan → task_step_done → task_complete / task_fail. Timeouts und Bridge-Ausfälle erscheinen als echte Fehler — das Seitenpanel zeigt Live-Fortschritt.', pt:'Silêncio não é mais sucesso. A IA declara task_plan → task_step_done → task_complete / task_fail. Timeouts e quedas de bridge aparecem como falhas reais — o painel lateral renderiza o progresso ao vivo.', ru:'Тишина больше не означает успех. ИИ явно объявляет task_plan → task_step_done → task_complete / task_fail. Таймауты и обрывы отображаются как настоящие сбои — боковая панель показывает прогресс в реальном времени.', ar:'الصمت لم يعد يعني النجاح. يُعلن الذكاء الاصطناعي task_plan → task_step_done → task_complete / task_fail. تظهر انتهاءات المهلة وانقطاع الجسر كإخفاقات حقيقية — يُصيّر الشريط الجانبي تقدم الخطوات مباشرةً.', it:'Il silenzio non è più successo. L\'IA dichiara task_plan → task_step_done → task_complete / task_fail. Timeout e disconnessioni appaiono come veri fallimenti — il pannello laterale mostra il progresso in tempo reale.', hi:'चुप्पी अब सफलता नहीं है। AI task_plan → task_step_done → task_complete / task_fail स्पष्ट रूप से घोषित करता है। टाइमआउट और ब्रिज ड्रॉप असली विफलताओं के रूप में दिखते हैं——साइड पैनल लाइव स्टेप प्रोगेस दिखाता है।' },
  'feat.7.title':     { en:'Multi-Account Parallel Control', zh:'多账号并行控制', ja:'マルチアカウント並列制御', ko:'멀티 계정 병렬 제어', es:'Control Paralelo Multi-Cuenta', fr:'Contrôle Parallèle Multi-Compte', de:'Multi-Account-Parallelsteuerung', pt:'Controle Paralelo Multi-Conta', ru:'Параллельное управление несколькими аккаунтами', ar:'التحكم المتوازي بحسابات متعددة', it:'Controllo Parallelo Multi-Account', hi:'मल्टी-अकाउंट पैरेलल कंट्रोल' },
  'feat.7.desc':      { en:'Run one task across multiple Chrome profiles at once — different accounts, same command. Each profile has explicit identity, can be suspended independently, and receives the full task lifecycle broadcast.', zh:'一条命令，多个 Chrome Profile 同时执行——不同账号，同一指令。每个 Profile 有独立身份标识，可单独挂起，并接收完整的任务生命周期广播。', ja:'複数のChromeプロファイルに一度にタスクを実行——別アカウント、同じコマンド。各プロファイルは独自の識別子を持ち、個別に停止でき、完全なタスクライフサイクルをブロードキャストで受信。', ko:'여러 Chrome 프로필에 한 번에 하나의 작업 실행——다른 계정, 같은 명령. 각 프로필은 명시적 신원을 가지고, 독립적으로 일시 정지할 수 있으며, 전체 작업 수명 주기 브로드캐스트를 받습니다.', es:'Ejecuta una tarea en varios perfiles de Chrome a la vez — distintas cuentas, el mismo comando. Cada perfil tiene identidad explícita, puede suspenderse de forma independiente y recibe la difusión completa del ciclo de vida de la tarea.', fr:'Exécutez une tâche sur plusieurs profils Chrome à la fois — comptes différents, même commande. Chaque profil a une identité explicite, peut être suspendu indépendamment et reçoit la diffusion complète du cycle de vie des tâches.', de:'Führe eine Aufgabe auf mehreren Chrome-Profilen gleichzeitig aus — verschiedene Konten, derselbe Befehl. Jedes Profil hat eine explizite Identität, kann unabhängig angehalten werden und empfängt den vollständigen Task-Lifecycle-Broadcast.', pt:'Execute uma tarefa em vários perfis do Chrome de uma vez — contas diferentes, mesmo comando. Cada perfil tem identidade explícita, pode ser suspenso independentemente e recebe a transmissão completa do ciclo de vida da tarefa.', ru:'Запустите одну задачу на нескольких профилях Chrome одновременно — разные аккаунты, одна команда. У каждого профиля явная идентичность, его можно приостановить независимо, и он получает полную рассылку жизненного цикла задачи.', ar:'شغّل مهمة واحدة عبر ملفات تعريف Chrome متعددة دفعة واحدة — حسابات مختلفة، أمر واحد. لكل ملف تعريف هوية صريحة، ويمكن إيقافه بشكل مستقل، ويستقبل بث دورة حياة المهمة الكاملة.', it:'Esegui un\'attività su più profili Chrome contemporaneamente — account diversi, stesso comando. Ogni profilo ha un\'identità esplicita, può essere sospeso indipendentemente e riceve la trasmissione completa del ciclo di vita del task.', hi:'एक बार में कई Chrome प्रोफाइल पर एक काम चलाएं——अलग-अलग अकाउंट, एक कमांड। हर प्रोफाइल की स्पष्ट पहचान होती है, उसे अलग से रोका जा सकता है, और वह पूरा टास्क लाइफसाइकल ब्रॉडकास्ट प्राप्त करता है।' },

  // ── Agents ──
  'agents.label':     { en:'Works with these AI coding agents', zh:'适配以下 AI 编程工具', ja:'以下のAIコーディングエージェントに対応', ko:'다음 AI 코딩 에이전트와 호환', es:'Compatible con estos agentes de programación IA', fr:'Fonctionne avec ces agents de programmation IA', de:'Funktioniert mit diesen KI-Coding-Agenten', pt:'Funciona com estes agentes de programação IA', ru:'Работает с этими ИИ-агентами для кода', ar:'يعمل مع وكلاء البرمجة بالذكاء الاصطناعي', it:'Compatibile con questi agenti di programmazione IA', hi:'इन AI कोडिंग एजेंट्स के साथ काम करता है' },

  // ── Muscle Highlight ──
  'muscle.label':     { en:'The Core Idea', zh:'核心理念', ja:'核心アイデア', ko:'핵심 아이디어', es:'La Idea Central', fr:'L\'Idée Centrale', de:'Die Kernidee', pt:'A Ideia Central', ru:'Ключевая идея', ar:'الفكرة الأساسية', it:'L\'Idea Centrale', hi:'मुख्य विचार' },
  'muscle.title':     { en:'AI has no memory. Give it one.', zh:'AI 没有记忆。给它一个。', ja:'AIに記憶がない。与えよう。', ko:'AI에게 기억이 없습니다. 기억을 주세요.', es:'La IA no tiene memoria. Dale una.', fr:'L\'IA n\'a pas de mémoire. Donnez-lui une.', de:'KI hat kein Gedächtnis. Gib ihr eines.', pt:'A IA não tem memória. Dê uma a ela.', ru:'У ИИ нет памяти. Дайте ему память.', ar:'الذكاء الاصطناعي لا ذاكرة له. أعطِه واحدة.', it:'L\'IA non ha memoria. Dàgliene una.', hi:'AI के पास कोई याददाश्त नहीं। उसे एक दें।' },

  // ── Architecture ──
  'arch.label':       { en:'Architecture', zh:'架构', ja:'アーキテクチャ', ko:'아키텍처', es:'Arquitectura', fr:'Architecture', de:'Architektur', pt:'Arquitetura', ru:'Архитектура', ar:'البنية', it:'Architettura', hi:'आर्किटेक्चर' },
  'arch.title':       { en:'Three layers. All localhost. Zero cloud.', zh:'三层架构。全部本地。零云端。', ja:'3層構造。すべてローカル。クラウドなし。', ko:'3개 레이어. 모두 로컬. 클라우드 제로.', es:'Tres capas. Todo local. Cero nube.', fr:'Trois couches. Tout en local. Zéro cloud.', de:'Drei Schichten. Alles lokal. Null Cloud.', pt:'Três camadas. Tudo local. Zero nuvem.', ru:'Три слоя. Всё локально. Ноль облака.', ar:'ثلاث طبقات. كل شيء محلي. بدون سحابة.', it:'Tre livelli. Tutto locale. Zero cloud.', hi:'तीन लेयर। सब लोकल। ज़ीरो क्लाउड।' },

  // ── Quick Start ──
  'start.label':      { en:'Quick Start', zh:'快速开始', ja:'クイックスタート', ko:'빠른 시작', es:'Inicio Rápido', fr:'Démarrage Rapide', de:'Schnellstart', pt:'Início Rápido', ru:'Быстрый старт', ar:'بداية سريعة', it:'Avvio Rapido', hi:'क्विक स्टार्ट' },
  'start.title':      { en:'Up and running in 2 minutes', zh:'2 分钟内开始运行', ja:'2分で起動', ko:'2분 만에 시작', es:'Funcionando en 2 minutos', fr:'Opérationnel en 2 minutes', de:'In 2 Minuten einsatzbereit', pt:'Funcionando em 2 minutos', ru:'Запуск за 2 минуты', ar:'جاهز في دقيقتين', it:'Operativo in 2 minuti', hi:'2 मिनट में शुरू करें' },

  // ── Pages ──
  'page.news.label':  { en:'News & Insights', zh:'新闻与洞察', ja:'ニュース＆インサイト', ko:'뉴스 & 인사이트', es:'Noticias y Perspectivas', fr:'Actualités et Perspectives', de:'Nachrichten & Einblicke', pt:'Notícias e Insights', ru:'Новости и аналитика', ar:'الأخبار والرؤى', it:'Notizie e Approfondimenti', hi:'समाचार और अंतर्दृष्टि' },
  'page.news.title':  { en:'AI Agents & Automation News', zh:'AI 智能体与自动化新闻', ja:'AIエージェント＆オートメーションニュース', ko:'AI 에이전트 & 자동화 뉴스', es:'Noticias de Agentes IA y Automatización', fr:'Actualités Agents IA et Automatisation', de:'KI-Agenten & Automatisierungs-Nachrichten', pt:'Notícias de Agentes IA e Automação', ru:'Новости ИИ-агентов и автоматизации', ar:'أخبار وكلاء الذكاء الاصطناعي والأتمتة', it:'Notizie Agenti IA e Automazione', hi:'AI एजेंट और ऑटोमेशन समाचार' },
  'page.tools.label': { en:'AI Tools Directory', zh:'AI 工具导航', ja:'AIツールディレクトリ', ko:'AI 도구 디렉토리', es:'Directorio de Herramientas IA', fr:'Répertoire d\'Outils IA', de:'KI-Tools-Verzeichnis', pt:'Diretório de Ferramentas IA', ru:'Каталог ИИ-инструментов', ar:'دليل أدوات الذكاء الاصطناعي', it:'Directory Strumenti IA', hi:'AI उपकरण निर्देशिका' },
  'page.tools.title': { en:'The Best AI Tools for Developers', zh:'开发者最佳 AI 工具导航', ja:'開発者のための最高のAIツール', ko:'개발자를 위한 최고의 AI 도구', es:'Las Mejores Herramientas IA para Desarrolladores', fr:'Les Meilleurs Outils IA pour Développeurs', de:'Die Besten KI-Tools für Entwickler', pt:'As Melhores Ferramentas IA para Desenvolvedores', ru:'Лучшие ИИ-инструменты для разработчиков', ar:'أفضل أدوات الذكاء الاصطناعي للمطورين', it:'I Migliori Strumenti IA per Sviluppatori', hi:'डेवलपर्स के लिए सर्वश्रेष्ठ AI उपकरण' },
  'page.tut.label':   { en:'Tutorials & Guides', zh:'教程与指南', ja:'チュートリアル＆ガイド', ko:'튜토리얼 & 가이드', es:'Tutoriales y Guías', fr:'Tutoriels et Guides', de:'Tutorials & Anleitungen', pt:'Tutoriais e Guias', ru:'Руководства', ar:'الدروس والأدلة', it:'Tutorial e Guide', hi:'ट्यूटोरियल और गाइड' },
  'page.tut.title':   { en:'Learn AgentLimb', zh:'学习 AgentLimb', ja:'AgentLimbを学ぶ', ko:'AgentLimb 배우기', es:'Aprende AgentLimb', fr:'Apprendre AgentLimb', de:'AgentLimb lernen', pt:'Aprenda AgentLimb', ru:'Изучайте AgentLimb', ar:'تعلم AgentLimb', it:'Impara AgentLimb', hi:'AgentLimb सीखें' },
  'page.tut.desc':    { en:'Step-by-step tutorials, use cases, and best practices for browser automation with AI.', zh:'逐步教程、使用案例和 AI 浏览器自动化最佳实践。', ja:'AIによるブラウザ自動化のチュートリアル、ユースケース、ベストプラクティス。', ko:'AI 브라우저 자동화를 위한 단계별 튜토리얼, 사용 사례 및 모범 사례.', es:'Tutoriales paso a paso, casos de uso y mejores prácticas para la automatización del navegador con IA.', fr:'Tutoriels étape par étape, cas d\'usage et bonnes pratiques pour l\'automatisation du navigateur avec l\'IA.', de:'Schritt-für-Schritt-Tutorials, Anwendungsfälle und Best Practices für Browser-Automatisierung mit KI.', pt:'Tutoriais passo a passo, casos de uso e melhores práticas para automação do navegador com IA.', ru:'Пошаговые руководства, примеры использования и лучшие практики автоматизации браузера с ИИ.', ar:'دروس خطوة بخطوة وحالات استخدام وأفضل الممارسات لأتمتة المتصفح بالذكاء الاصطناعي.', it:'Tutorial passo-passo, casi d\'uso e best practice per l\'automazione del browser con l\'IA.', hi:'AI के साथ ब्राउज़र ऑटोमेशन के लिए चरण-दर-चरण ट्यूटोरियल, उपयोग केस और सर्वोत्तम प्रथाएं।' },
  'page.news.desc':   { en:'Curated updates on AI coding tools, browser automation, and the agentic AI ecosystem.', zh:'精选 AI 编程工具、浏览器自动化和智能体生态的最新动态。', ja:'AIコーディングツール、ブラウザ自動化、エージェントAIエコシステムの厳選アップデート。', ko:'AI 코딩 도구, 브라우저 자동화 및 에이전트 AI 생태계에 대한 큐레이션된 업데이트.', es:'Actualizaciones seleccionadas sobre herramientas de codificación IA, automatización del navegador y el ecosistema de IA agéntica.', fr:'Mises à jour sélectionnées sur les outils de codage IA, l\'automatisation du navigateur et l\'écosystème IA agentique.', de:'Kuratierte Updates zu KI-Coding-Tools, Browser-Automatisierung und dem agentischen KI-Ökosystem.', pt:'Atualizações curadas sobre ferramentas de codificação IA, automação do navegador e o ecossistema de IA agêntica.', ru:'Подборка новостей об ИИ-инструментах для кодинга, автоматизации браузера и экосистеме агентного ИИ.', ar:'تحديثات منتقاة حول أدوات البرمجة بالذكاء الاصطناعي وأتمتة المتصفح ونظام الذكاء الاصطناعي الوكيل.', it:'Aggiornamenti curati su strumenti di codifica IA, automazione del browser e l\'ecosistema IA agentivo.', hi:'AI कोडिंग टूल्स, ब्राउज़र ऑटोमेशन और एजेंटिक AI इकोसिस्टम पर क्यूरेटेड अपडेट।' },
  'page.tools.desc':  { en:'Curated collection of AI coding agents, models, automation platforms, and dev tools.', zh:'精选 AI 编程工具、模型、自动化平台和开发工具合集。', ja:'AIコーディングエージェント、モデル、自動化プラットフォーム、開発ツールの厳選コレクション。', ko:'AI 코딩 에이전트, 모델, 자동화 플랫폼 및 개발 도구의 큐레이션된 컬렉션.', es:'Colección curada de agentes de codificación IA, modelos, plataformas de automatización y herramientas de desarrollo.', fr:'Collection sélectionnée d\'agents de codage IA, modèles, plateformes d\'automatisation et outils de développement.', de:'Kuratierte Sammlung von KI-Coding-Agenten, Modellen, Automatisierungsplattformen und Entwickler-Tools.', pt:'Coleção curada de agentes de codificação IA, modelos, plataformas de automação e ferramentas de desenvolvimento.', ru:'Подборка ИИ-агентов для кодинга, моделей, платформ автоматизации и инструментов разработки.', ar:'مجموعة منتقاة من وكلاء البرمجة بالذكاء الاصطناعي والنماذج ومنصات الأتمتة وأدوات التطوير.', it:'Raccolta curata di agenti di codifica IA, modelli, piattaforme di automazione e strumenti di sviluppo.', hi:'AI कोडिंग एजेंट, मॉडल, ऑटोमेशन प्लेटफॉर्म और डेव टूल्स का क्यूरेटेड कलेक्शन।' },

  // ── Use Cases ──
  'uc.label':         { en:'Built For', zh:'适合的人', ja:'こんな方に', ko:'이런 분들을 위해', es:'Hecho Para', fr:'Fait Pour', de:'Gemacht Für', pt:'Feito Para', ru:'Создано для', ar:'مصنوع لـ', it:'Fatto Per', hi:'इनके लिए' },
  'uc.title':         { en:'People who do the same thing every day.', zh:'每天都在重复做同一件事的人。', ja:'毎日同じことをしている人たちへ。', ko:'매일 같은 일을 하는 사람들.', es:'Personas que hacen lo mismo cada día.', fr:'Les gens qui font la même chose chaque jour.', de:'Menschen, die jeden Tag dasselbe tun.', pt:'Pessoas que fazem a mesma coisa todos os dias.', ru:'Люди, которые делают одно и то же каждый день.', ar:'الأشخاص الذين يفعلون نفس الشيء كل يوم.', it:'Persone che fanno la stessa cosa ogni giorno.', hi:'वो लोग जो हर दिन एक ही काम करते हैं।' },
  'uc.desc':          { en:'You\'re not lazy. You just know that repetition is a waste of your time — and your tokens.', zh:'你不是懒，你只是明白重复是在浪费时间——还有 token。', ja:'怠けているのではありません。ただ、繰り返しは時間とトークンの無駄だと知っているだけ。', ko:'게으른 게 아닙니다. 반복이 시간과 토큰의 낭비라는 걸 알기 때문입니다.', es:'No eres perezoso. Solo sabes que la repetición es un desperdicio de tu tiempo — y de tus tokens.', fr:'Vous n\'êtes pas paresseux. Vous savez juste que la répétition est un gaspillage de temps — et de tokens.', de:'Du bist nicht faul. Du weißt nur, dass Wiederholung eine Verschwendung deiner Zeit ist — und deiner Tokens.', pt:'Você não é preguiçoso. Você simplesmente sabe que repetição é um desperdício de tempo — e de tokens.', ru:'Вы не ленивы. Просто знаете, что повторение — это потеря времени и токенов.', ar:'لست كسولاً. أنت فقط تعرف أن التكرار هدر لوقتك — ولرموزك.', it:'Non sei pigro. Sai solo che la ripetizione è uno spreco di tempo — e di token.', hi:'आप आलसी नहीं हैं। आप बस जानते हैं कि दोहराव आपके समय की बर्बादी है——और टोकन की भी।' },
  'uc.1.title':       { en:'The Daily Marketer', zh:'每天做推广的人', ja:'毎日マーケティングする人', ko:'매일 마케팅하는 사람', es:'El Marketer Diario', fr:'Le Marketeur du Quotidien', de:'Der tägliche Marketer', pt:'O Marketer Diário', ru:'Ежедневный маркетолог', ar:'المسوّق اليومي', it:'Il Marketer Quotidiano', hi:'रोज़ाना मार्केटिंग करने वाला' },
  'uc.1.desc':        { en:'Post to 5 platforms without opening a tab. Engage communities, run campaigns — all through your real accounts, zero re-login.', zh:'不用打开标签页就能发布到 5 个平台。用你的真实账号经营社区、跑活动——零重复登录。', ja:'タブを開かずに5つのプラットフォームに投稿。本物のアカウントでコミュニティ運営、キャンペーン実行——ゼロ再ログイン。', ko:'탭을 열지 않고 5개 플랫폼에 게시합니다. 실제 계정으로 커뮤니티 운영, 캠페인 진행——재로그인 제로.', es:'Publica en 5 plataformas sin abrir una pestaña. Gestiona comunidades, ejecuta campañas — todo con tus cuentas reales, cero re-login.', fr:'Publiez sur 5 plateformes sans ouvrir un onglet. Gérez des communautés, lancez des campagnes — via vos vrais comptes, zéro reconnexion.', de:'Poste auf 5 Plattformen ohne einen Tab zu öffnen. Verwalte Communities, führe Kampagnen durch — alles über deine echten Accounts, null erneutes Einloggen.', pt:'Publique em 5 plataformas sem abrir uma aba. Gerencie comunidades, execute campanhas — tudo através de suas contas reais, zero re-login.', ru:'Публикуйте на 5 платформах без открытия вкладки. Управляйте сообществами, ведите кампании — через ваши реальные аккаунты, ноль повторных входов.', ar:'انشر على 5 منصات دون فتح تبويب. أدر المجتمعات، نفّذ الحملات — عبر حساباتك الحقيقية، بدون إعادة تسجيل دخول.', it:'Pubblica su 5 piattaforme senza aprire un tab. Gestisci community, esegui campagne — tutto tramite i tuoi account reali, zero re-login.', hi:'कोई टैब खोले बिना 5 प्लेटफ़ॉर्म पर पोस्ट करें। अपने असली अकाउंट से कम्युनिटी चलाएं, कैंपेन करें——शून्य दोबारा लॉगिन।' },
  'uc.2.title':       { en:'The Lazy Researcher', zh:'懒得重复的研究者', ja:'繰り返しが嫌いなリサーチャー', ko:'반복이 싫은 연구자', es:'El Investigador Eficiente', fr:'Le Chercheur Malin', de:'Der smarte Forscher', pt:'O Pesquisador Eficiente', ru:'Умный исследователь', ar:'الباحث الذكي', it:'Il Ricercatore Furbo', hi:'दोहराव से थका हुआ रिसर्चर' },
  'uc.2.desc':        { en:'Collect data, compare products, track competitors. Your AI runs the route; the muscle handles the next hundred times.', zh:'收集数据、对比产品、追踪竞品。AI 跑路，肌肉处理接下来的一百次。', ja:'データ収集、製品比較、競合追跡。AIがルートを走り、マッスルが次の百回を処理。', ko:'데이터 수집, 제품 비교, 경쟁사 추적. AI가 경로를 실행하고 근육이 다음 백 번을 처리합니다.', es:'Recopila datos, compara productos, rastrea competidores. Tu IA corre la ruta; el músculo maneja las próximas cien veces.', fr:'Collectez des données, comparez des produits, suivez les concurrents. Votre IA parcourt la route ; le muscle gère les cent prochaines fois.', de:'Sammle Daten, vergleiche Produkte, verfolge Konkurrenten. Deine KI läuft die Route; der Muskel übernimmt die nächsten hundert Male.', pt:'Colete dados, compare produtos, rastreie concorrentes. Sua IA roda o caminho; o músculo lida com as próximas cem vezes.', ru:'Собирайте данные, сравнивайте продукты, отслеживайте конкурентов. ИИ проходит маршрут; мускул обрабатывает следующие сто раз.', ar:'اجمع البيانات، قارن المنتجات، تتبع المنافسين. ذكاؤك الاصطناعي يسلك المسار؛ العضلة تتعامل مع المئة مرة القادمة.', it:'Raccogli dati, confronta prodotti, traccia i concorrenti. La tua IA percorre il tragitto; il muscolo gestisce le prossime cento volte.', hi:'डेटा इकट्ठा करें, प्रोडक्ट तुलना करें, प्रतिस्पर्धियों को ट्रैक करें। AI रूट चलाता है; मसल अगली सौ बार संभालता है।' },
  'uc.3.title':       { en:'The Repeat Operator', zh:'反复执行操作的人', ja:'繰り返し作業をする人', ko:'반복 작업자', es:'El Operador Repetitivo', fr:'L\'Opérateur Répétitif', de:'Der Routine-Arbeiter', pt:'O Operador Repetitivo', ru:'Оператор рутинных задач', ar:'مشغّل المهام المتكررة', it:'L\'Operatore Ripetitivo', hi:'दोहराने वाला ऑपरेटर' },
  'uc.3.desc':        { en:'Forms, applications, profile updates, submissions. Record once. Run whenever. No manual steps.', zh:'表单、申请、账号更新、批量提交。记录一次，随时运行，零手动步骤。', ja:'フォーム、申請、プロフィール更新、送信。一度記録。いつでも実行。手動ステップなし。', ko:'폼, 신청, 프로필 업데이트, 제출. 한 번 기록. 언제든 실행. 수동 단계 없음.', es:'Formularios, solicitudes, actualizaciones de perfil, envíos. Graba una vez. Ejecuta cuando quieras. Sin pasos manuales.', fr:'Formulaires, candidatures, mises à jour de profil, soumissions. Enregistre une fois. Exécute quand tu veux. Aucune étape manuelle.', de:'Formulare, Anträge, Profil-Updates, Einreichungen. Einmal aufnehmen. Wann immer ausführen. Keine manuellen Schritte.', pt:'Formulários, inscrições, atualizações de perfil, envios. Grave uma vez. Execute quando quiser. Sem etapas manuais.', ru:'Формы, заявки, обновления профиля, отправки. Запись один раз. Запуск когда угодно. Без ручных шагов.', ar:'نماذج، طلبات، تحديثات الملف الشخصي، تقديمات. سجّل مرة واحدة. شغّل متى شئت. بدون خطوات يدوية.', it:'Moduli, candidature, aggiornamenti profilo, invii. Registra una volta. Esegui quando vuoi. Nessun passaggio manuale.', hi:'फॉर्म, आवेदन, प्रोफाइल अपडेट, सबमिशन। एक बार रिकॉर्ड करें। जब चाहें चलाएं। कोई मैनुअल स्टेप नहीं।' },
  'uc.4.title':       { en:'The QA Engineer', zh:'QA 工程师', ja:'QAエンジニア', ko:'QA 엔지니어', es:'El Ingeniero de QA', fr:'L\'Ingénieur QA', de:'Der QA-Ingenieur', pt:'O Engenheiro de QA', ru:'QA-инженер', ar:'مهندس ضمان الجودة', it:'L\'Ingegnere QA', hi:'QA इंजीनियर' },
  'uc.4.desc':        { en:'Test real flows on a real browser with real sessions. Save the test path as a muscle — rerun with one command.', zh:'在真实浏览器、真实登录态上测试真实流程。将测试路径存为肌肉——一条命令重跑。', ja:'実際のブラウザ、実際のセッションで実際のフローをテスト。テストパスをマッスルとして保存——1コマンドで再実行。', ko:'실제 브라우저, 실제 세션으로 실제 플로우를 테스트합니다. 테스트 경로를 근육으로 저장——명령 하나로 재실행.', es:'Prueba flujos reales en un navegador real con sesiones reales. Guarda el camino de prueba como músculo — re-ejecuta con un comando.', fr:'Testez de vrais flux sur un vrai navigateur avec de vraies sessions. Sauvegardez le chemin de test comme muscle — relancez avec une commande.', de:'Teste echte Flows in einem echten Browser mit echten Sitzungen. Speichere den Testpfad als Muskel — führe ihn mit einem Befehl erneut aus.', pt:'Teste fluxos reais em um navegador real com sessões reais. Salve o caminho de teste como músculo — reexecute com um comando.', ru:'Тестируйте реальные потоки в реальном браузере с реальными сессиями. Сохраните тестовый путь как мускул — запустите повторно одной командой.', ar:'اختبر التدفقات الحقيقية في متصفح حقيقي مع جلسات حقيقية. احفظ مسار الاختبار كعضلة — أعد التشغيل بأمر واحد.', it:'Testa flussi reali su un browser reale con sessioni reali. Salva il percorso di test come muscolo — ri-esegui con un comando.', hi:'वास्तविक ब्राउज़र में वास्तविक सत्रों के साथ वास्तविक फ्लो टेस्ट करें। टेस्ट पाथ को मसल के रूप में सेव करें——एक कमांड से दोबारा चलाएं।' },

  // ── Quick Start Steps ──
  'start.desc':       { en:'Three steps. No build tools. No config files.', zh:'三步。无需构建工具。无需配置文件。', ja:'3ステップ。ビルドツール不要。設定ファイル不要。', ko:'3단계. 빌드 도구 없음. 설정 파일 없음.', es:'Tres pasos. Sin herramientas de compilación. Sin archivos de configuración.', fr:'Trois étapes. Pas d\'outils de build. Pas de fichiers de config.', de:'Drei Schritte. Keine Build-Tools. Keine Config-Dateien.', pt:'Três passos. Sem ferramentas de build. Sem arquivos de config.', ru:'Три шага. Без инструментов сборки. Без файлов конфигурации.', ar:'ثلاث خطوات. بدون أدوات بناء. بدون ملفات تكوين.', it:'Tre passaggi. Nessun tool di build. Nessun file di configurazione.', hi:'तीन चरण। कोई बिल्ड टूल नहीं। कोई कॉन्फ़िग फ़ाइल नहीं।' },
  'start.s1.title':   { en:'Install the Extension', zh:'安装扩展', ja:'拡張機能をインストール', ko:'확장 프로그램 설치', es:'Instalar la Extensión', fr:'Installer l\'Extension', de:'Extension installieren', pt:'Instalar a Extensão', ru:'Установите расширение', ar:'تثبيت الإضافة', it:'Installa l\'Estensione', hi:'एक्सटेंशन इंस्टॉल करें' },
  'start.s1.desc':    { en:'Add from the Chrome Web Store, or clone and load as unpacked.', zh:'从 Chrome 应用商店添加，或克隆后以开发者模式加载。', ja:'Chrome Web Storeから追加、またはクローンしてアンパックとしてロード。', ko:'Chrome 웹 스토어에서 추가하거나 클론 후 압축 해제로 로드합니다.', es:'Añade desde Chrome Web Store, o clona y carga como desempaquetado.', fr:'Ajoutez depuis le Chrome Web Store, ou clonez et chargez en mode décompressé.', de:'Aus dem Chrome Web Store hinzufügen oder klonen und entpackt laden.', pt:'Adicione da Chrome Web Store, ou clone e carregue como descompactado.', ru:'Добавьте из Chrome Web Store или клонируйте и загрузите в распакованном виде.', ar:'أضف من متجر Chrome الإلكتروني، أو انسخ المستودع وحمّله كملف غير مضغوط.', it:'Aggiungi dal Chrome Web Store, o clona e carica come non compresso.', hi:'Chrome वेब स्टोर से जोड़ें, या क्लोन करें और अनपैक्ड लोड करें।' },
  'start.s2.title':   { en:'Start the Bridge', zh:'启动 Bridge', ja:'Bridgeを起動', ko:'Bridge 시작', es:'Iniciar el Bridge', fr:'Démarrer le Bridge', de:'Bridge starten', pt:'Iniciar o Bridge', ru:'Запустите Bridge', ar:'تشغيل الجسر', it:'Avvia il Bridge', hi:'Bridge शुरू करें' },
  'start.s2.desc':    { en:'One command launches the local bridge — connects your AI to Chrome.', zh:'一条命令启动本地 bridge — 将你的 AI 连接到 Chrome。', ja:'1つのコマンドでローカルブリッジを起動 — AIをChromeに接続。', ko:'하나의 명령으로 로컬 bridge를 시작 — AI를 Chrome에 연결합니다.', es:'Un comando lanza el bridge local — conecta tu IA a Chrome.', fr:'Une commande lance le bridge local — connecte votre IA à Chrome.', de:'Ein Befehl startet die lokale Bridge — verbindet deine KI mit Chrome.', pt:'Um comando inicia o bridge local — conecta sua IA ao Chrome.', ru:'Одна команда запускает локальный мост — подключает ваш ИИ к Chrome.', ar:'أمر واحد يشغل الجسر المحلي — يربط ذكاءك الاصطناعي بـ Chrome.', it:'Un comando avvia il bridge locale — connette la tua IA a Chrome.', hi:'एक कमांड लोकल bridge शुरू करता है — आपके AI को Chrome से जोड़ता है।' },
  'start.s3.title':   { en:'Copy the Prompt, Paste to Your AI', zh:'复制提示词，粘贴给你的 AI', ja:'プロンプトをコピーしてAIに貼り付け', ko:'프롬프트를 복사하여 AI에 붙여넣기', es:'Copia el Prompt, Pégalo en tu IA', fr:'Copiez le Prompt, Collez-le dans votre IA', de:'Prompt kopieren, in deine KI einfügen', pt:'Copie o Prompt, Cole na sua IA', ru:'Скопируйте промпт, вставьте в ваш ИИ', ar:'انسخ الموجه، والصقه في ذكائك الاصطناعي', it:'Copia il Prompt, Incollalo nella tua IA', hi:'प्रॉम्प्ट कॉपी करें, अपने AI में पेस्ट करें' },
  'start.s3.desc':    { en:'Open the AgentLimb side panel, click "Copy Onboard Prompt", paste it to any AI tool. Your AI can now see and control your browser.', zh:'打开 AgentLimb 侧边栏，点击"复制接入提示词"，粘贴给任何 AI 工具。你的 AI 现在可以看到并控制你的浏览器了。', ja:'AgentLimbサイドパネルを開き、「接続プロンプトをコピー」をクリックし、AIツールに貼り付けます。AIがブラウザを見て操作できるようになります。', ko:'AgentLimb 사이드 패널을 열고 "온보드 프롬프트 복사"를 클릭하여 AI 도구에 붙여넣으세요. AI가 이제 브라우저를 보고 제어할 수 있습니다.', es:'Abre el panel lateral de AgentLimb, haz clic en "Copiar Prompt de Incorporación", pégalo en cualquier herramienta IA. Tu IA ahora puede ver y controlar tu navegador.', fr:'Ouvrez le panneau latéral AgentLimb, cliquez sur "Copier le Prompt", collez-le dans n\'importe quel outil IA. Votre IA peut maintenant voir et contrôler votre navigateur.', de:'Öffne das AgentLimb-Seitenpanel, klicke auf "Prompt kopieren", füge es in ein beliebiges KI-Tool ein. Deine KI kann jetzt deinen Browser sehen und steuern.', pt:'Abra o painel lateral do AgentLimb, clique em "Copiar Prompt de Integração", cole em qualquer ferramenta IA. Sua IA agora pode ver e controlar seu navegador.', ru:'Откройте боковую панель AgentLimb, нажмите «Копировать промпт», вставьте в любой ИИ-инструмент. Ваш ИИ теперь может видеть и управлять вашим браузером.', ar:'افتح اللوحة الجانبية لـ AgentLimb، انقر على "نسخ موجه البدء"، الصقه في أي أداة ذكاء اصطناعي. يمكن لذكائك الاصطناعي الآن رؤية متصفحك والتحكم فيه.', it:'Apri il pannello laterale di AgentLimb, clicca su "Copia Prompt di Onboarding", incollalo in qualsiasi strumento IA. La tua IA ora può vedere e controllare il tuo browser.', hi:'AgentLimb साइड पैनल खोलें, "ऑनबोर्ड प्रॉम्प्ट कॉपी करें" पर क्लिक करें, किसी भी AI टूल में पेस्ट करें। आपका AI अब आपके ब्राउज़र को देख और नियंत्रित कर सकता है।' },

  // ── Muscle Store ──
  'store.badge':      { en:'Coming Soon', zh:'即将上线', ja:'近日公開', ko:'출시 예정', es:'Próximamente', fr:'Bientôt', de:'Demnächst', pt:'Em Breve', ru:'Скоро', ar:'قريبًا', it:'Prossimamente', hi:'जल्द आ रहा है' },
  'store.title':      { en:'Muscle Library', zh:'肌肉库', ja:'マッスルライブラリ', ko:'근육 라이브러리', es:'Biblioteca de Músculos', fr:'Bibliothèque de Muscles', de:'Muskel-Bibliothek', pt:'Biblioteca de Músculos', ru:'Библиотека мускулов', ar:'مكتبة العضلات', it:'Libreria Muscoli', hi:'मसल लाइब्रेरी' },
  'store.desc':       { en:'Discover, share, and download community-built muscles. Automate new platforms without exploration — just install a muscle and run.', zh:'发现、分享和下载社区构建的肌肉。无需探索即可自动化新平台 — 安装肌肉即可运行。', ja:'コミュニティが作成したマッスルを発見・共有・ダウンロード。探索なしで新しいプラットフォームを自動化 — マッスルをインストールして実行するだけ。', ko:'커뮤니티가 만든 근육을 발견, 공유, 다운로드하세요. 탐색 없이 새 플랫폼 자동화 — 근육을 설치하고 실행하기만 하면 됩니다.', es:'Descubre, comparte y descarga músculos creados por la comunidad. Automatiza nuevas plataformas sin exploración — solo instala un músculo y ejecuta.', fr:'Découvrez, partagez et téléchargez des muscles créés par la communauté. Automatisez de nouvelles plateformes sans exploration — installez un muscle et exécutez.', de:'Entdecke, teile und lade Community-Muskeln herunter. Automatisiere neue Plattformen ohne Erkundung — installiere einen Muskel und starte.', pt:'Descubra, compartilhe e baixe músculos criados pela comunidade. Automatize novas plataformas sem exploração — instale um músculo e execute.', ru:'Находите, делитесь и загружайте мускулы, созданные сообществом. Автоматизируйте новые платформы без исследования — установите мускул и запустите.', ar:'اكتشف وشارك وحمّل عضلات أنشأها المجتمع. أتمت منصات جديدة بدون استكشاف — فقط ثبّت عضلة وشغّلها.', it:'Scopri, condividi e scarica muscoli creati dalla community. Automatizza nuove piattaforme senza esplorazione — installa un muscolo ed esegui.', hi:'समुदाय द्वारा बनाए गए मसल्स खोजें, साझा करें और डाउनलोड करें। एक्सप्लोरेशन के बिना नए प्लेटफॉर्म को ऑटोमेट करें — बस एक मसल इंस्टॉल करें और चलाएं।' },
  'store.cta':        { en:'Star the repo to get notified when Muscle Store launches.', zh:'给仓库加星以获取肌肉商店上线通知。', ja:'マッスルストアのローンチ通知を受け取るにはリポジトリにスターを。', ko:'Muscle Store 출시 알림을 받으려면 저장소에 스타를 표시하세요.', es:'Dale estrella al repo para recibir notificación cuando se lance Muscle Store.', fr:'Mettez une étoile au repo pour être notifié du lancement du Magasin de Muscles.', de:'Gib dem Repo einen Stern, um benachrichtigt zu werden, wenn der Muskel-Store startet.', pt:'Dê uma estrela ao repo para ser notificado quando a Loja de Músculos for lançada.', ru:'Поставьте звезду репозиторию, чтобы получить уведомление о запуске Магазина мускулов.', ar:'ضع نجمة على المستودع لتلقي إشعار عند إطلاق متجر العضلات.', it:'Metti una stella al repo per essere notificato quando il Negozio Muscoli verrà lanciato.', hi:'Muscle Store लॉन्च होने पर सूचना पाने के लिए रेपो को स्टार करें।' },

  // ── Article Page ──
  'article.back.tut': { en:'Back to Tutorials', zh:'返回教程', ja:'チュートリアルに戻る', ko:'튜토리얼로 돌아가기', es:'Volver a Tutoriales', fr:'Retour aux Tutoriels', de:'Zurück zu Tutorials', pt:'Voltar para Tutoriais', ru:'Назад к руководствам', ar:'العودة إلى الدروس', it:'Torna ai Tutorial', hi:'ट्यूटोरियल पर वापस जाएं' },
  'article.back.news':{ en:'Back to News', zh:'返回新闻', ja:'ニュースに戻る', ko:'뉴스로 돌아가기', es:'Volver a Noticias', fr:'Retour aux Actualités', de:'Zurück zu Nachrichten', pt:'Voltar para Notícias', ru:'Назад к новостям', ar:'العودة إلى الأخبار', it:'Torna alle Notizie', hi:'समाचार पर वापस जाएं' },
  'article.loading':  { en:'Loading...', zh:'加载中…', ja:'読み込み中…', ko:'로딩 중...', es:'Cargando...', fr:'Chargement...', de:'Laden...', pt:'Carregando...', ru:'Загрузка...', ar:'جار التحميل...', it:'Caricamento...', hi:'लोड हो रहा है...' },
  'article.notfound': { en:'Article not found.', zh:'文章未找到。', ja:'記事が見つかりません。', ko:'기사를 찾을 수 없습니다.', es:'Artículo no encontrado.', fr:'Article introuvable.', de:'Artikel nicht gefunden.', pt:'Artigo não encontrado.', ru:'Статья не найдена.', ar:'المقال غير موجود.', it:'Articolo non trovato.', hi:'लेख नहीं मिला।' },

  // ── Common ──
  'common.back':      { en:'Back to home', zh:'返回首页', ja:'ホームに戻る', ko:'홈으로 돌아가기', es:'Volver al inicio', fr:'Retour à l\'accueil', de:'Zurück zur Startseite', pt:'Voltar ao início', ru:'На главную', ar:'العودة إلى الرئيسية', it:'Torna alla home', hi:'होम पर वापस जाएं' },

  // ── Muscle Compare Table ──
  'cmp.explore':      { en:'First Explore', zh:'首次探索', ja:'初回探索', ko:'첫 탐색', es:'Primera Exploración', fr:'Première Exploration', de:'Erste Erkundung', pt:'Primeira Exploração', ru:'Первое исследование', ar:'الاستكشاف الأول', it:'Prima Esplorazione', hi:'पहली खोज' },
  'cmp.replay':       { en:'Muscle Replay', zh:'肌肉回放', ja:'マッスルリプレイ', ko:'근육 리플레이', es:'Reproducción Muscular', fr:'Replay Musculaire', de:'Muskel-Replay', pt:'Replay Muscular', ru:'Воспроизведение мускула', ar:'إعادة تشغيل العضلة', it:'Replay Muscolare', hi:'मसल रीप्ले' },
  'cmp.calls':        { en:'API Calls', zh:'API 调用', ja:'API呼び出し', ko:'API 호출', es:'Llamadas API', fr:'Appels API', de:'API-Aufrufe', pt:'Chamadas API', ru:'API-вызовы', ar:'استدعاءات API', it:'Chiamate API', hi:'API कॉल' },
  'cmp.tokens':       { en:'Tokens', zh:'Token 消耗', ja:'トークン', ko:'토큰', es:'Tokens', fr:'Tokens', de:'Tokens', pt:'Tokens', ru:'Токены', ar:'الرموز', it:'Token', hi:'टोकन' },
  'cmp.errors':       { en:'Errors', zh:'错误', ja:'エラー', ko:'오류', es:'Errores', fr:'Erreurs', de:'Fehler', pt:'Erros', ru:'Ошибки', ar:'الأخطاء', it:'Errori', hi:'त्रुटियां' },
  'cmp.possible':     { en:'Possible', zh:'可能', ja:'あり得る', ko:'가능', es:'Posible', fr:'Possible', de:'Möglich', pt:'Possível', ru:'Возможны', ar:'محتمل', it:'Possibili', hi:'संभव' },
  'cmp.result':       { en:'90% Token Reduction', zh:'减少 90% Token 消耗', ja:'トークン90%削減', ko:'토큰 90% 절감', es:'90% Reducción de Tokens', fr:'90% Réduction de Tokens', de:'90% Token-Reduzierung', pt:'90% Redução de Tokens', ru:'На 90% меньше токенов', ar:'تقليل الرموز بنسبة 90%', it:'90% Riduzione Token', hi:'90% टोकन कमी' },

  // ── Muscle Memory paragraphs ──
  'muscle.p1':        { en:'Every time your AI posts on Reddit, it rediscovers where the button is. Every time it fills a form, it re-reads the page from scratch. You\'re paying tokens for work it already did yesterday.', zh:'每次你让 AI 在 Reddit 发帖，它都要重新找一遍按钮在哪。每次填表，它都从头读一遍页面。你在用 token 付账，让它做昨天就做过的事。', ja:'AIがRedditに投稿するたびにボタンがどこにあるか再発見します。フォームを入力するたびにページを最初から読みます。昨日やった作業にトークンを支払っています。', ko:'AI가 Reddit에 게시할 때마다 버튼이 어디 있는지 다시 찾습니다. 폼을 채울 때마다 페이지를 처음부터 읽습니다. 어제 이미 한 작업에 토큰을 내고 있습니다.', es:'Cada vez que tu IA publica en Reddit, redescubre dónde está el botón. Cada vez que llena un formulario, relee la página desde cero. Estás pagando tokens por trabajo que ya hizo ayer.', fr:'Chaque fois que votre IA poste sur Reddit, elle redécouvre où est le bouton. Chaque fois qu\'elle remplit un formulaire, elle relit la page depuis le début. Vous payez des tokens pour du travail qu\'elle a déjà fait hier.', de:'Jedes Mal, wenn deine KI auf Reddit postet, entdeckt sie neu, wo der Button ist. Jedes Mal, wenn sie ein Formular ausfüllt, liest sie die Seite von vorne. Du zahlst Tokens für Arbeit, die sie gestern bereits gemacht hat.', pt:'Cada vez que sua IA posta no Reddit, redescobre onde fica o botão. Cada vez que preenche um formulário, relê a página do zero. Você está pagando tokens por trabalho que ela já fez ontem.', ru:'Каждый раз, когда ваш ИИ публикует на Reddit, он заново обнаруживает, где кнопка. Каждый раз, заполняя форму, перечитывает страницу с нуля. Вы платите токены за работу, которую он уже сделал вчера.', ar:'في كل مرة ينشر فيها ذكاؤك الاصطناعي على Reddit، يعيد اكتشاف مكان الزر. في كل مرة يملأ فيها نموذجًا، يعيد قراءة الصفحة من البداية. أنت تدفع رموزًا مقابل عمل قام به بالأمس.', it:'Ogni volta che la tua IA posta su Reddit, riscopre dove si trova il pulsante. Ogni volta che compila un modulo, rilegge la pagina da capo. Stai pagando token per lavoro che ha già fatto ieri.', hi:'हर बार जब आपका AI Reddit पर पोस्ट करता है, वह बटन कहाँ है यह फिर से ढूंढता है। हर बार जब वह फॉर्म भरता है, पेज शुरू से पढ़ता है। आप उस काम के लिए टोकन दे रहे हैं जो उसने कल भी किया था।' },
  'muscle.p2':        { en:'AgentLimb records that route as a "muscle." Next run: one command, zero exploration, the same result — without the re-learning tax.', zh:'AgentLimb 把这条路径记录为一块「肌肉」。下次运行：一条命令，零探索，同样的结果——没有重新学习的成本。', ja:'AgentLimbはそのルートを「マッスル」として記録します。次の実行：1コマンド、探索ゼロ、同じ結果——再学習コストなし。', ko:'AgentLimb는 그 경로를 \'근육\'으로 기록합니다. 다음 실행: 명령 하나, 탐색 제로, 같은 결과——재학습 비용 없음.', es:'AgentLimb registra esa ruta como un "músculo". Próxima ejecución: un comando, cero exploración, el mismo resultado — sin el costo de re-aprendizaje.', fr:'AgentLimb enregistre cette route comme un "muscle". Prochaine exécution : une commande, zéro exploration, le même résultat — sans le coût de ré-apprentissage.', de:'AgentLimb zeichnet diese Route als "Muskel" auf. Nächste Ausführung: ein Befehl, null Erkundung, dasselbe Ergebnis — ohne den Neu-Lern-Aufwand.', pt:'AgentLimb registra essa rota como um "músculo". Próxima execução: um comando, zero exploração, o mesmo resultado — sem o custo de re-aprendizado.', ru:'AgentLimb записывает этот маршрут как «мускул». Следующий запуск: одна команда, ноль исследований, тот же результат — без затрат на повторное обучение.', ar:'AgentLimb يسجل هذا المسار كـ"عضلة". التشغيل التالي: أمر واحد، استكشاف صفر، نفس النتيجة — بدون تكلفة إعادة التعلم.', it:'AgentLimb registra quel percorso come "muscolo". Prossima esecuzione: un comando, zero esplorazione, lo stesso risultato — senza il costo del ri-apprendimento.', hi:'AgentLimb उस रूट को \'मसल\' के रूप में रिकॉर्ड करता है। अगला रन: एक कमांड, शून्य एक्सप्लोरेशन, वही परिणाम——दोबारा सीखने की कोई लागत नहीं।' },
  'muscle.p3':        { en:'One exploration per platform. Saved permanently. The more you reuse, the more you save.', zh:'每个平台只需探索一次，永久保存。复用越多，节省越多。', ja:'プラットフォームごとに探索1回。永久保存。再利用するほど節約できます。', ko:'플랫폼당 탐색 한 번. 영구 저장. 재사용할수록 더 많이 절약됩니다.', es:'Una exploración por plataforma. Guardada permanentemente. Cuanto más reutilices, más ahorras.', fr:'Une exploration par plateforme. Sauvegardée définitivement. Plus vous réutilisez, plus vous économisez.', de:'Eine Erkundung pro Plattform. Dauerhaft gespeichert. Je mehr du wiederverwendest, desto mehr sparst du.', pt:'Uma exploração por plataforma. Salva permanentemente. Quanto mais reutilizar, mais economizará.', ru:'Одно исследование на платформу. Сохранено навсегда. Чем больше используете повторно, тем больше экономите.', ar:'استكشاف واحد لكل منصة. محفوظ بشكل دائم. كلما أعدت الاستخدام، وفّرت أكثر.', it:'Un\'esplorazione per piattaforma. Salvata permanentemente. Più riutilizzi, più risparmi.', hi:'प्रति प्लेटफ़ॉर्म एक एक्सप्लोरेशन। हमेशा के लिए सेव। जितना अधिक रीयूज़, उतनी अधिक बचत।' },

  // ── Architecture section ──
  'arch.desc':        { en:'8 standardized MCP tools. Any AI that can send HTTP or use MCP can drive your browser.', zh:'8 个标准化 MCP 工具。任何能发送 HTTP 或使用 MCP 的 AI 都能驱动你的浏览器。', ja:'8つの標準化MCPツール。HTTPを送信またはMCPを使用できるAIならブラウザを操作できます。', ko:'8개의 표준화된 MCP 도구. HTTP를 보내거나 MCP를 사용할 수 있는 모든 AI가 브라우저를 구동할 수 있습니다.', es:'8 herramientas MCP estandarizadas. Cualquier IA que pueda enviar HTTP o usar MCP puede controlar tu navegador.', fr:'8 outils MCP standardisés. Toute IA capable d\'envoyer du HTTP ou d\'utiliser MCP peut piloter votre navigateur.', de:'8 standardisierte MCP-Tools. Jede KI, die HTTP senden oder MCP nutzen kann, kann deinen Browser steuern.', pt:'8 ferramentas MCP padronizadas. Qualquer IA que possa enviar HTTP ou usar MCP pode controlar seu navegador.', ru:'8 стандартизированных MCP-инструментов. Любой ИИ, способный отправлять HTTP или использовать MCP, может управлять вашим браузером.', ar:'8 أدوات MCP معيارية. أي ذكاء اصطناعي يمكنه إرسال HTTP أو استخدام MCP يمكنه التحكم في متصفحك.', it:'8 strumenti MCP standardizzati. Qualsiasi IA che può inviare HTTP o usare MCP può guidare il tuo browser.', hi:'8 मानकीकृत MCP उपकरण। HTTP भेज सकने वाला या MCP उपयोग कर सकने वाला कोई भी AI आपके ब्राउज़र को चला सकता है।' },
  'arch.ai':          { en:'Your AI Tool', zh:'你的 AI 工具', ja:'あなたのAIツール', ko:'당신의 AI 도구', es:'Tu Herramienta IA', fr:'Votre Outil IA', de:'Dein KI-Tool', pt:'Sua Ferramenta IA', ru:'Ваш ИИ-инструмент', ar:'أداة الذكاء الاصطناعي', it:'Il Tuo Strumento IA', hi:'आपका AI टूल' },
  'arch.bridge':      { en:'AgentLimb Bridge', zh:'AgentLimb 桥接', ja:'AgentLimb ブリッジ', ko:'AgentLimb 브릿지', es:'AgentLimb Bridge', fr:'AgentLimb Bridge', de:'AgentLimb Bridge', pt:'AgentLimb Bridge', ru:'AgentLimb Мост', ar:'جسر AgentLimb', it:'AgentLimb Bridge', hi:'AgentLimb ब्रिज' },
  'arch.ext':         { en:'AgentLimb Extension', zh:'AgentLimb 扩展', ja:'AgentLimb 拡張機能', ko:'AgentLimb 확장 프로그램', es:'Extensión AgentLimb', fr:'Extension AgentLimb', de:'AgentLimb Extension', pt:'Extensão AgentLimb', ru:'Расширение AgentLimb', ar:'إضافة AgentLimb', it:'Estensione AgentLimb', hi:'AgentLimb एक्सटेंशन' },
  'arch.browser':     { en:'Your Browser', zh:'你的浏览器', ja:'あなたのブラウザ', ko:'당신의 브라우저', es:'Tu Navegador', fr:'Votre Navigateur', de:'Dein Browser', pt:'Seu Navegador', ru:'Ваш браузер', ar:'متصفحك', it:'Il Tuo Browser', hi:'आपका ब्राउज़र' },
  'arch.browser.sub': { en:'logged in · cookies · real sessions', zh:'已登录 · cookies · 真实会话', ja:'ログイン済み · クッキー · 実セッション', ko:'로그인 상태 · 쿠키 · 실제 세션', es:'sesión iniciada · cookies · sesiones reales', fr:'connecté · cookies · sessions réelles', de:'eingeloggt · Cookies · echte Sitzungen', pt:'logado · cookies · sessões reais', ru:'авторизован · куки · реальные сессии', ar:'مسجل الدخول · ملفات تعريف الارتباط · جلسات حقيقية', it:'connesso · cookie · sessioni reali', hi:'लॉग्ड इन · कुकीज़ · वास्तविक सत्र' },

  // ── Quick Start (revised: 10-second config) ──
  'start.title2':     { en:'Up and running in under a minute.', zh:'一分钟内跑起来。', ja:'1分以内に起動。', ko:'1분 이내에 시작.', es:'En marcha en menos de un minuto.', fr:'Opérationnel en moins d\'une minute.', de:'In unter einer Minute einsatzbereit.', pt:'Funcionando em menos de um minuto.', ru:'Готово менее чем за минуту.', ar:'جاهز في أقل من دقيقة.', it:'Operativo in meno di un minuto.', hi:'एक मिनट से कम में तैयार।' },
  'start.desc2':      { en:'No account. No API key. No cloud. Install the extension, then copy one prompt.', zh:'无需账号、API Key 或云端。安装扩展，再复制一个提示词。', ja:'アカウント不要。APIキー不要。クラウド不要。Chrome拡張機能と1つのプロンプトだけ。', ko:'계정 불필요. API 키 불필요. 클라우드 불필요. Chrome 확장 프로그램과 프롬프트 하나.', es:'Sin cuenta. Sin API key. Sin nube. Solo una extensión de Chrome y un prompt.', fr:'Pas de compte. Pas de clé API. Pas de cloud. Juste une extension Chrome et un prompt.', de:'Kein Konto. Kein API-Schlüssel. Keine Cloud. Nur eine Chrome-Erweiterung und ein Prompt.', pt:'Sem conta. Sem API key. Sem nuvem. Apenas uma extensão do Chrome e um prompt.', ru:'Без аккаунта. Без API-ключа. Без облака. Просто расширение Chrome и один промпт.', ar:'بدون حساب. بدون مفتاح API. بدون سحابة. فقط إضافة Chrome وموجه واحد.', it:'Nessun account. Nessuna API key. Nessun cloud. Solo un\'estensione Chrome e un prompt.', hi:'कोई अकाउंट नहीं। कोई API Key नहीं। कोई क्लाउड नहीं। बस एक Chrome एक्सटेंशन और एक प्रॉम्प्ट।' },
  'start.s1.title2':  { en:'Install the Extension', zh:'安装扩展程序', ja:'拡張機能をインストール', ko:'확장 프로그램 설치', es:'Instalar Extensión', fr:'Installer l\'Extension', de:'Extension installieren', pt:'Instalar Extensão', ru:'Установите расширение', ar:'ثبّت الإضافة', it:'Installa Estensione', hi:'एक्सटेंशन इंस्टॉल करें' },
  'start.s1.desc2':   { en:'Install from the Chrome Web Store, or load the extension zip from GitHub Releases.', zh:'从 Chrome 应用商店安装，或从 GitHub Releases 下载扩展压缩包后加载。', ja:'zipをダウンロードして解凍、chrome://extensionsを開き、デベロッパーモードを有効化、パッケージ化されていない拡張機能を読み込む。', ko:'zip을 다운로드하여 압축 해제, chrome://extensions 열기, 개발자 모드 활성화, 압축 해제된 확장 프로그램 로드 클릭.', es:'Descarga el zip, descomprímelo, abre chrome://extensions, activa el Modo Desarrollador, haz clic en Cargar descomprimida.', fr:'Télécharge le zip, décompresse-le, ouvre chrome://extensions, active le Mode Développeur, clique sur Charger l\'extension non empaquetée.', de:'zip herunterladen, entpacken, chrome://extensions öffnen, Entwicklermodus aktivieren, Entpackte Erweiterung laden klicken.', pt:'Baixe o zip, descompacte, abra chrome://extensions, ative o Modo Desenvolvedor, clique em Carregar sem compactação.', ru:'Скачайте zip, распакуйте, откройте chrome://extensions, включите Режим разработчика, нажмите Загрузить распакованное расширение.', ar:'حمّل الملف المضغوط، افتحه، افتح chrome://extensions، فعّل وضع المطور، انقر تحميل الإضافة غير المعبأة.', it:'Scarica lo zip, estrailo, apri chrome://extensions, attiva la Modalità Sviluppatore, clicca Carica estensione non pacchettizzata.', hi:'zip डाउनलोड करें, अनज़िप करें, chrome://extensions खोलें, Developer Mode चालू करें, Load unpacked पर क्लिक करें।' },
  'start.s2.title2':  { en:'Install the Local Runtime', zh:'安装本地运行时', ja:'ローカルランタイムをインストール', ko:'로컬 런타임 설치', es:'Instalar el entorno local', fr:'Installer le runtime local', de:'Lokale Runtime installieren', pt:'Instalar o runtime local', ru:'Установите локальную среду', ar:'ثبّت وقت التشغيل المحلي', it:'Installa il runtime locale', hi:'लोकल रनटाइम इंस्टॉल करें' },
  'start.s2.desc2':   { en:'Copy the onboarding prompt. After approval, it downloads the matching GitHub version tag and configures the local Runtime.', zh:'复制接入提示词。经你确认后，它会下载匹配的 GitHub 版本 tag 并配置本地运行时。', ja:'オンボーディングプロンプトをコピーします。承認後、Windows または macOS のローカル拡張パッケージからランタイムを設定します。', ko:'온보딩 프롬프트를 복사하세요. 승인 후 Windows 또는 macOS의 로컬 확장 패키지에서 런타임을 설정합니다.', es:'Copia el prompt de inicio. Tras tu aprobación, configura el entorno local desde la extensión instalada en Windows o macOS.', fr:'Copiez le prompt d’intégration. Après votre accord, il configure le runtime local depuis l’extension installée sous Windows ou macOS.', de:'Kopiere den Einrichtungs-Prompt. Nach deiner Zustimmung richtet er die lokale Runtime aus der installierten Erweiterung unter Windows oder macOS ein.', pt:'Copie o prompt de integração. Após sua aprovação, ele configura o runtime local a partir da extensão instalada no Windows ou macOS.', ru:'Скопируйте вводный запрос. После подтверждения он настроит локальную среду из установленного расширения в Windows или macOS.', ar:'انسخ موجّه الإعداد. بعد موافقتك، يضبط وقت التشغيل المحلي من الإضافة المثبتة على Windows أو macOS.', it:'Copia il prompt di configurazione. Dopo la tua approvazione, configura il runtime locale dall’estensione installata su Windows o macOS.', hi:'ऑनबोर्डिंग प्रॉम्प्ट कॉपी करें। आपकी मंजूरी के बाद यह Windows या macOS में इंस्टॉल किए गए एक्सटेंशन पैकेज से लोकल रनटाइम सेट करता है।' },
  'start.s3.title2':  { en:'Paste to Any AI', zh:'粘贴给任何 AI', ja:'どのAIにも貼り付け', ko:'모든 AI에 붙여넣기', es:'Pegar en Cualquier IA', fr:'Coller dans n\'importe quel IA', de:'In Jede KI Einfügen', pt:'Colar em Qualquer IA', ru:'Вставить в любой ИИ', ar:'لصق في أي ذكاء اصطناعي', it:'Incolla in Qualsiasi IA', hi:'किसी भी AI में पेस्ट करें' },
  'start.s3.desc2':   { en:'Paste to Claude Code, Cursor, Codex, or anything that runs commands. It auto-configures and starts working immediately.', zh:'粘贴给 Claude Code、Cursor、Codex，或任何能运行命令的工具。自动配置，立即开始工作。', ja:'Claude Code、Cursor、Codex、またはコマンドを実行できるツールに貼り付け。自動設定で即座に動作開始。', ko:'Claude Code, Cursor, Codex 또는 명령을 실행할 수 있는 도구에 붙여넣으세요. 자동 구성 후 즉시 작동합니다.', es:'Pega en Claude Code, Cursor, Codex, o cualquier cosa que ejecute comandos. Se auto-configura y empieza a trabajar inmediatamente.', fr:'Collez dans Claude Code, Cursor, Codex, ou tout ce qui exécute des commandes. Il se configure automatiquement et commence à travailler immédiatement.', de:'Füge in Claude Code, Cursor, Codex oder alles, was Befehle ausführt, ein. Es konfiguriert sich automatisch und beginnt sofort zu arbeiten.', pt:'Cole em Claude Code, Cursor, Codex, ou qualquer coisa que execute comandos. Ele se auto-configura e começa a trabalhar imediatamente.', ru:'Вставьте в Claude Code, Cursor, Codex или что угодно, что выполняет команды. Автонастройка и мгновенный старт.', ar:'الصق في Claude Code أو Cursor أو Codex أو أي شيء يشغّل الأوامر. يتم إعداده تلقائيًا ويبدأ العمل فورًا.', it:'Incolla in Claude Code, Cursor, Codex, o qualsiasi cosa esegua comandi. Si auto-configura e inizia a lavorare immediatamente.', hi:'Claude Code, Cursor, Codex, या कोई भी कमांड चलाने वाले टूल में पेस्ट करें। ऑटो-कॉन्फ़िगर होकर तुरंत काम शुरू करता है।' },

  // ── Comparison Table ──
  'compare.label':      { en:'Why AgentLimb', zh:'为什么选择 AgentLimb', ja:'AgentLimbを選ぶ理由', ko:'왜 AgentLimb인가', es:'Por qué AgentLimb', fr:'Pourquoi AgentLimb', de:'Warum AgentLimb', pt:'Por que AgentLimb', ru:'Почему AgentLimb', ar:'لماذا AgentLimb', it:'Perché AgentLimb', hi:'AgentLimb क्यों' },
  'compare.title':      { en:'Every other approach has a real cost.', zh:'其他每一种方案都有真实的代价。', ja:'他のどのアプローチにもコストがある。', ko:'다른 모든 접근 방식에는 실제 비용이 있습니다.', es:'Cada otro enfoque tiene un coste real.', fr:'Chaque autre approche a un coût réel.', de:'Jeder andere Ansatz hat echte Kosten.', pt:'Toda outra abordagem tem um custo real.', ru:'У каждого другого подхода есть реальная цена.', ar:'لكل نهج آخر تكلفة حقيقية.', it:'Ogni altro approccio ha un costo reale.', hi:'हर दूसरे दृष्टिकोण की एक वास्तविक कीमत है।' },
  'compare.desc':       { en:'Browser automation has been solved — badly — four different ways. Here\'s the honest breakdown.', zh:'浏览器自动化已经被解决过——用四种方式，每种都有代价。这是一份诚实的拆解。', ja:'ブラウザ自動化は4通りの方法で——どれも不完全に——解決されてきました。正直な比較です。', ko:'브라우저 자동화는 네 가지 방식으로——모두 불완전하게——해결되어 왔습니다. 정직한 비교입니다.', es:'La automatización del navegador se ha resuelto — mal — de cuatro maneras distintas. Aquí un desglose honesto.', fr:'L\'automatisation du navigateur a été résolue — mal — de quatre façons différentes. Voici une comparaison honnête.', de:'Browser-Automatisierung wurde auf vier Arten gelöst — keine davon wirklich gut. Hier der ehrliche Vergleich.', pt:'Automação de navegador foi resolvida — de forma imperfeita — de quatro maneiras diferentes. Aqui está uma comparação honesta.', ru:'Автоматизация браузера решалась — плохо — четырьмя разными способами. Вот честное сравнение.', ar:'تمت أتمتة المتصفح — بشكل رديء — بأربع طرق مختلفة. إليك المقارنة الصريحة.', it:'L\'automazione del browser è stata risolta — male — in quattro modi diversi. Ecco un confronto onesto.', hi:'ब्राउज़र ऑटोमेशन को चार अलग तरीकों से——ठीक से नहीं——हल किया गया है। यहाँ एक ईमानदार तुलना है।' },

  'compare.r.setup':    { en:'Setup', zh:'配置', ja:'セットアップ', ko:'설정', es:'Configuración', fr:'Configuration', de:'Einrichtung', pt:'Configuração', ru:'Настройка', ar:'الإعداد', it:'Configurazione', hi:'सेटअप' },
  'compare.r.target':   { en:'Element targeting', zh:'元素定位', ja:'要素の特定', ko:'요소 타겟팅', es:'Identificación de elementos', fr:'Ciblage d\'éléments', de:'Element-Erkennung', pt:'Identificação de elementos', ru:'Выбор элементов', ar:'تحديد العناصر', it:'Targeting elementi', hi:'एलिमेंट टार्गेटिंग' },
  'compare.r.token':    { en:'Token cost per action', zh:'每次动作 Token 成本', ja:'操作ごとのトークンコスト', ko:'작업당 토큰 비용', es:'Coste de tokens por acción', fr:'Coût par action en tokens', de:'Token-Kosten pro Aktion', pt:'Custo de tokens por ação', ru:'Стоимость токенов за действие', ar:'تكلفة الرموز لكل عملية', it:'Costo token per azione', hi:'प्रति क्रिया टोकन लागत' },
  'compare.r.repeat':   { en:'Repeat task cost', zh:'重复任务成本', ja:'繰り返しタスクのコスト', ko:'반복 작업 비용', es:'Coste de tareas repetidas', fr:'Coût des tâches répétées', de:'Kosten für wiederholte Aufgaben', pt:'Custo de tarefas repetidas', ru:'Стоимость повторных задач', ar:'تكلفة المهام المتكررة', it:'Costo task ripetuti', hi:'दोहराए गए कार्य की लागत' },
  'compare.r.login':    { en:'Login sessions', zh:'登录会话', ja:'ログインセッション', ko:'로그인 세션', es:'Sesiones de inicio', fr:'Sessions de connexion', de:'Login-Sitzungen', pt:'Sessões de login', ru:'Сессии входа', ar:'جلسات تسجيل الدخول', it:'Sessioni di login', hi:'लॉगिन सत्र' },
  'compare.r.update':   { en:'When the site updates', zh:'网站更新时', ja:'サイト更新時', ko:'사이트 업데이트 시', es:'Cuando el sitio cambia', fr:'Quand le site change', de:'Wenn die Seite sich ändert', pt:'Quando o site muda', ru:'Когда сайт обновляется', ar:'عند تحديث الموقع', it:'Quando il sito cambia', hi:'जब साइट अपडेट होती है' },
  'compare.r.privacy':  { en:'Data privacy', zh:'数据隐私', ja:'データプライバシー', ko:'데이터 프라이버시', es:'Privacidad de datos', fr:'Confidentialité des données', de:'Datenschutz', pt:'Privacidade de dados', ru:'Конфиденциальность данных', ar:'خصوصية البيانات', it:'Privacy dei dati', hi:'डेटा गोपनीयता' },
  'compare.r.choice':   { en:'AI terminal choice', zh:'AI 终端选择', ja:'AIターミナルの選択', ko:'AI 터미널 선택', es:'Elección de terminal IA', fr:'Choix de terminal IA', de:'KI-Terminal-Auswahl', pt:'Escolha do terminal IA', ru:'Выбор ИИ-терминала', ar:'اختيار طرفية الذكاء الاصطناعي', it:'Scelta del terminale IA', hi:'AI टर्मिनल विकल्प' },
  'compare.r.shared':   { en:'Shared knowledge', zh:'知识共享', ja:'知識の共有', ko:'공유 지식', es:'Conocimiento compartido', fr:'Connaissance partagée', de:'Gemeinsames Wissen', pt:'Conhecimento compartilhado', ru:'Общие знания', ar:'المعرفة المشتركة', it:'Conoscenza condivisa', hi:'साझा ज्ञान' },

  'compare.r.setup.a':  { en:'Write scripts, manage dependencies, handle headless mode', zh:'编写脚本、管理依赖、处理无头模式', ja:'スクリプトを書き、依存関係を管理し、ヘッドレスモードに対処', ko:'스크립트 작성, 의존성 관리, 헤드리스 모드 처리', es:'Escribir scripts, gestionar dependencias, manejar modo headless', fr:'Écrire des scripts, gérer les dépendances, configurer le mode headless', de:'Skripte schreiben, Abhängigkeiten verwalten, Headless-Modus handhaben', pt:'Escrever scripts, gerenciar dependências, lidar com modo headless', ru:'Писать скрипты, управлять зависимостями, настраивать headless-режим', ar:'كتابة سكربتات، إدارة التبعيات، التعامل مع الوضع بلا واجهة', it:'Scrivere script, gestire dipendenze, gestire modalità headless', hi:'स्क्रिप्ट लिखना, डिपेंडेंसी मैनेज करना, हेडलेस मोड संभालना' },
  'compare.r.setup.b':  { en:'SaaS config, per-workflow setup', zh:'SaaS 配置，按工作流单独设置', ja:'SaaSの設定、ワークフローごとのセットアップ', ko:'SaaS 설정, 워크플로우별 구성', es:'Config SaaS, configuración por flujo', fr:'Config SaaS, configuration par workflow', de:'SaaS-Konfiguration, pro Workflow einzeln', pt:'Config SaaS, setup por fluxo', ru:'SaaS-конфигурация, настройка под каждый сценарий', ar:'إعداد SaaS، إعداد منفصل لكل سير عمل', it:'Config SaaS, setup per singolo workflow', hi:'SaaS कॉन्फ़िग, प्रति-वर्कफ़्लो सेटअप' },
  'compare.r.setup.c':  { en:'Mac only (needs desktop env), sandbox required', zh:'仅支持 Mac(需桌面环境),需要沙盒', ja:'Macのみ(デスクトップ環境が必要)、サンドボックス必須', ko:'Mac 전용 (데스크톱 환경 필요), 샌드박스 필수', es:'Solo Mac (requiere entorno de escritorio), sandbox obligatorio', fr:'Mac uniquement (besoin d\'un environnement desktop), sandbox requis', de:'Nur Mac (braucht Desktop-Umgebung), Sandbox erforderlich', pt:'Só Mac (requer ambiente desktop), sandbox obrigatório', ru:'Только Mac (нужна рабочая среда), требуется песочница', ar:'Mac فقط (يحتاج بيئة سطح المكتب)، صندوق حماية مطلوب', it:'Solo Mac (serve ambiente desktop), sandbox richiesta', hi:'केवल Mac (डेस्कटॉप वातावरण चाहिए), sandbox आवश्यक' },
  'compare.r.setup.d':  { en:'Copy one prompt. Done.', zh:'复制一个提示词,搞定。', ja:'プロンプトを1つコピー。完了。', ko:'프롬프트 하나 복사. 끝.', es:'Copia un prompt. Listo.', fr:'Copiez un prompt. Fini.', de:'Einen Prompt kopieren. Fertig.', pt:'Copie um prompt. Pronto.', ru:'Скопируйте один промпт. Готово.', ar:'انسخ موجّهًا واحدًا. انتهى.', it:'Copia un prompt. Fatto.', hi:'एक प्रॉम्प्ट कॉपी करें। हो गया।' },

  'compare.r.target.a': { en:'CSS/XPath — you write and maintain them', zh:'CSS/XPath——由你编写和维护', ja:'CSS/XPath——自分で書いて保守', ko:'CSS/XPath——직접 작성하고 유지 관리', es:'CSS/XPath — tú los escribes y mantienes', fr:'CSS/XPath — vous les écrivez et maintenez', de:'CSS/XPath — du schreibst und pflegst sie', pt:'CSS/XPath — você os escreve e mantém', ru:'CSS/XPath — вы пишете и поддерживаете их', ar:'CSS/XPath — أنت تكتبها وتصونها', it:'CSS/XPath — li scrivi e mantieni tu', hi:'CSS/XPath——आप इन्हें लिखते और मेंटेन करते हैं' },
  'compare.r.target.b': { en:'Visual AI detection — unstable on updates', zh:'视觉 AI 识别——网站更新时不稳定', ja:'視覚AI検出——サイト更新時に不安定', ko:'시각 AI 감지——업데이트 시 불안정', es:'Detección visual por IA — inestable ante cambios', fr:'Détection IA visuelle — instable face aux mises à jour', de:'Visuelle KI-Erkennung — instabil bei Updates', pt:'Detecção visual por IA — instável em atualizações', ru:'Визуальное распознавание ИИ — нестабильно при обновлениях', ar:'كشف مرئي بالذكاء الاصطناعي — غير مستقر عند التحديثات', it:'Rilevamento visivo IA — instabile negli aggiornamenti', hi:'विज़ुअल AI डिटेक्शन——अपडेट पर अस्थिर' },
  'compare.r.target.c': { en:'Screenshot coordinates — ±1px can miss the target', zh:'截图坐标——偏差 ±1 像素就可能点错', ja:'スクリーンショット座標——±1ピクセルでズレる', ko:'스크린샷 좌표——±1픽셀이면 빗나갑니다', es:'Coordenadas de captura — ±1px puede fallar el objetivo', fr:'Coordonnées de capture — ±1px peut rater la cible', de:'Screenshot-Koordinaten — ±1px kann das Ziel verfehlen', pt:'Coordenadas de captura — ±1px pode errar o alvo', ru:'Координаты скриншота — ±1 пиксель может промахнуться', ar:'إحداثيات لقطة الشاشة — ±1 بكسل قد يخطئ الهدف', it:'Coordinate screenshot — ±1px può mancare il bersaglio', hi:'स्क्रीनशॉट कोऑर्डिनेट्स——±1px भी लक्ष्य चूक सकता है' },
  'compare.r.target.d': { en:'CDP reads the live DOM — semantic, precise', zh:'CDP 直读实时 DOM——语义化,精准', ja:'CDPがライブDOMを読む——セマンティックで正確', ko:'CDP가 실시간 DOM 직접 읽기——시맨틱, 정확', es:'CDP lee el DOM en vivo — semántico, preciso', fr:'CDP lit le DOM en direct — sémantique, précis', de:'CDP liest das Live-DOM — semantisch, präzise', pt:'CDP lê o DOM ao vivo — semântico, preciso', ru:'CDP читает живой DOM — семантично, точно', ar:'CDP يقرأ DOM المباشر — دلالي ودقيق', it:'CDP legge il DOM live — semantico, preciso', hi:'CDP लाइव DOM पढ़ता है——सिमेंटिक, सटीक' },

  'compare.r.token.a':  { en:'None (pure script)', zh:'零(纯脚本)', ja:'なし(純粋なスクリプト)', ko:'없음 (순수 스크립트)', es:'Ninguno (script puro)', fr:'Aucun (script pur)', de:'Keine (reines Skript)', pt:'Zero (script puro)', ru:'Нет (чистый скрипт)', ar:'لا شيء (سكربت خالص)', it:'Zero (script puro)', hi:'शून्य (सिर्फ स्क्रिप्ट)' },
  'compare.r.token.b':  { en:'Cloud fees + AI tokens', zh:'云服务费 + AI token', ja:'クラウド料金 + AIトークン', ko:'클라우드 요금 + AI 토큰', es:'Tarifas cloud + tokens de IA', fr:'Frais cloud + tokens IA', de:'Cloud-Gebühren + KI-Tokens', pt:'Taxas de cloud + tokens IA', ru:'Плата за облако + токены ИИ', ar:'رسوم سحابية + رموز الذكاء الاصطناعي', it:'Costi cloud + token IA', hi:'क्लाउड शुल्क + AI टोकन' },
  'compare.r.token.c':  { en:'1,000–3,000 tokens/screenshot × every step', zh:'1,000–3,000 token/截图 × 每一步', ja:'1,000〜3,000トークン/スクショ × 各ステップ', ko:'1,000–3,000 토큰/스크린샷 × 매 단계', es:'1.000–3.000 tokens/captura × cada paso', fr:'1 000–3 000 tokens/capture × chaque étape', de:'1.000–3.000 Tokens/Screenshot × jeder Schritt', pt:'1.000–3.000 tokens/screenshot × cada passo', ru:'1 000–3 000 токенов/скриншот × каждый шаг', ar:'1,000–3,000 رمز/لقطة شاشة × كل خطوة', it:'1.000–3.000 token/screenshot × ogni passaggio', hi:'1,000–3,000 टोकन/स्क्रीनशॉट × हर चरण' },
  'compare.r.token.d':  { en:'~300 tokens/step. Hot start: 85.7% less.', zh:'约 300 token/步。热启动可再省 85.7%。', ja:'約300トークン/ステップ。ホットスタート:85.7%削減。', ko:'약 300 토큰/단계. 핫 스타트: 85.7% 절감.', es:'~300 tokens/paso. Inicio en caliente: 85,7 % menos.', fr:'~300 tokens/étape. Démarrage à chaud : 85,7 % de moins.', de:'~300 Tokens/Schritt. Warmstart: 85,7 % weniger.', pt:'~300 tokens/passo. Início quente: 85,7% menos.', ru:'~300 токенов/шаг. Тёплый старт: на 85,7 % меньше.', ar:'~300 رمز/خطوة. البدء الساخن: أقل بنسبة 85.7%.', it:'~300 token/passo. Avvio a caldo: -85,7%.', hi:'~300 टोकन/चरण। हॉट स्टार्ट: 85.7% कम।' },

  'compare.r.repeat.a': { en:'Fixed (script re-runs)', zh:'固定(脚本重跑)', ja:'固定(スクリプトを再実行)', ko:'고정 (스크립트 재실행)', es:'Fijo (el script se vuelve a ejecutar)', fr:'Fixe (le script se relance)', de:'Konstant (Skript läuft erneut)', pt:'Fixo (o script roda de novo)', ru:'Фиксированная (скрипт перезапускается)', ar:'ثابت (إعادة تشغيل السكربت)', it:'Fisso (lo script viene rieseguito)', hi:'निश्चित (स्क्रिप्ट फिर से चलती है)' },
  'compare.r.repeat.b': { en:'Linear — billed per execution', zh:'线性增长——按次计费', ja:'線形——実行ごとに課金', ko:'선형 증가——실행마다 과금', es:'Lineal — se cobra por ejecución', fr:'Linéaire — facturé par exécution', de:'Linear — pro Ausführung abgerechnet', pt:'Linear — cobrado por execução', ru:'Линейно — оплата за каждый запуск', ar:'خطي — محاسبة لكل تنفيذ', it:'Lineare — addebito per esecuzione', hi:'रैखिक——प्रति निष्पादन शुल्क' },
  'compare.r.repeat.c': { en:'Linear — re-explores every time, no memory', zh:'线性增长——每次都重新探索,无记忆', ja:'線形——毎回再探索、記憶なし', ko:'선형 증가——매번 재탐색, 기억 없음', es:'Lineal — re-explora cada vez, sin memoria', fr:'Linéaire — re-explore à chaque fois, sans mémoire', de:'Linear — erkundet jedes Mal neu, kein Gedächtnis', pt:'Linear — reexplora cada vez, sem memória', ru:'Линейно — исследует заново каждый раз, без памяти', ar:'خطي — يعيد الاستكشاف في كل مرة، بلا ذاكرة', it:'Lineare — ri-esplora ogni volta, nessuna memoria', hi:'रैखिक——हर बार फिर से खोजता है, कोई मेमोरी नहीं' },
  'compare.r.repeat.d': { en:'Decreasing — muscle memory compounds', zh:'递减——肌肉记忆越用越省', ja:'逓減——マッスルメモリが積み上がる', ko:'감소——근육 기억이 누적됩니다', es:'Decreciente — la memoria muscular se acumula', fr:'Décroissant — la mémoire musculaire s\'accumule', de:'Sinkend — Muskelgedächtnis summiert sich', pt:'Decrescente — memória muscular se acumula', ru:'Снижается — мускульная память накапливается', ar:'متناقص — الذاكرة العضلية تتراكم', it:'Decrescente — la muscle memory si accumula', hi:'घटती हुई——मसल मेमोरी जुड़ती जाती है' },

  'compare.r.login.a':  { en:'Extra cookie/session setup', zh:'额外配置 Cookie/会话', ja:'クッキー/セッションの追加設定', ko:'쿠키/세션 별도 설정', es:'Configuración extra de cookies/sesiones', fr:'Configuration cookies/sessions en plus', de:'Zusätzliches Cookie-/Sitzungs-Setup', pt:'Setup extra de cookies/sessões', ru:'Дополнительная настройка cookie/сессий', ar:'إعداد إضافي لملفات تعريف الارتباط/الجلسات', it:'Setup extra di cookie/sessioni', hi:'अतिरिक्त कुकी/सत्र सेटअप' },
  'compare.r.login.b':  { en:'Cloud — can\'t use your local sessions', zh:'云端——无法使用你本地的登录态', ja:'クラウド——ローカルのセッションは使えない', ko:'클라우드——로컬 세션 사용 불가', es:'Cloud — no puedes usar tus sesiones locales', fr:'Cloud — impossible d\'utiliser vos sessions locales', de:'Cloud — kann deine lokalen Sitzungen nicht nutzen', pt:'Cloud — não usa suas sessões locais', ru:'Облако — локальные сессии недоступны', ar:'سحابي — لا يمكنه استخدام جلساتك المحلية', it:'Cloud — non può usare le tue sessioni locali', hi:'क्लाउड——आपके लोकल सत्र उपयोग नहीं कर सकता' },
  'compare.r.login.c':  { en:'OS-level, unaware of browser state', zh:'操作系统级别,感知不到浏览器状态', ja:'OSレベル、ブラウザの状態を認識しない', ko:'OS 레벨, 브라우저 상태를 모름', es:'A nivel SO, no conoce el estado del navegador', fr:'Au niveau OS, ignore l\'état du navigateur', de:'OS-Ebene, kennt den Browser-Status nicht', pt:'Nível do SO, sem saber o estado do navegador', ru:'На уровне ОС — не знает о состоянии браузера', ar:'على مستوى النظام، لا يدرك حالة المتصفح', it:'A livello OS, non conosce lo stato del browser', hi:'OS-स्तर, ब्राउज़र स्थिति से अनजान' },
  'compare.r.login.d':  { en:'Your real Chrome — already logged in', zh:'你的真实 Chrome——已经登录', ja:'あなたの本物のChrome——ログイン済み', ko:'실제 Chrome——이미 로그인됨', es:'Tu Chrome real — ya tienes sesión', fr:'Votre vrai Chrome — déjà connecté', de:'Dein echtes Chrome — schon eingeloggt', pt:'Seu Chrome real — já logado', ru:'Ваш настоящий Chrome — уже авторизованы', ar:'Chrome الحقيقي لديك — مسجّل الدخول بالفعل', it:'Il tuo vero Chrome — già loggato', hi:'आपका असली Chrome——पहले से लॉग-इन' },

  'compare.r.update.a': { en:'Selectors break — rewrite scripts', zh:'选择器失效——重写脚本', ja:'セレクタが壊れる——スクリプト書き直し', ko:'셀렉터 깨짐——스크립트 재작성', es:'Los selectores se rompen — reescribir scripts', fr:'Sélecteurs cassés — réécrire les scripts', de:'Selektoren brechen — Skripte neu schreiben', pt:'Os seletores quebram — reescreva scripts', ru:'Селекторы ломаются — переписывать скрипты', ar:'المحددات تتعطل — أعد كتابة السكربتات', it:'I selettori si rompono — riscrivi gli script', hi:'सिलेक्टर टूटते हैं——स्क्रिप्ट दोबारा लिखें' },
  'compare.r.update.b': { en:'Visual model may degrade silently', zh:'视觉模型可能悄无声息地退化', ja:'視覚モデルが静かに劣化する可能性', ko:'시각 모델이 조용히 저하될 수 있음', es:'El modelo visual puede degradarse en silencio', fr:'Le modèle visuel peut se dégrader silencieusement', de:'Das visuelle Modell kann sich unbemerkt verschlechtern', pt:'O modelo visual pode degradar silenciosamente', ru:'Визуальная модель может незаметно деградировать', ar:'قد يتدهور النموذج المرئي بصمت', it:'Il modello visivo può degradare silenziosamente', hi:'विज़ुअल मॉडल चुपचाप गिर सकता है' },
  'compare.r.update.c': { en:'Screenshot inference adjusts, but expensively', zh:'截图推理能调整,但开销很大', ja:'スクショ推論で対応できるが高コスト', ko:'스크린샷 추론으로 대응하지만 비쌉니다', es:'La inferencia de captura se ajusta, pero es cara', fr:'L\'inférence par capture s\'adapte, mais coûte cher', de:'Screenshot-Inferenz passt sich an, aber teuer', pt:'A inferência por screenshot se ajusta, mas sai cara', ru:'Скриншот-инференс подстраивается, но дорого', ar:'الاستدلال من لقطات الشاشة يتكيف، لكن بتكلفة عالية', it:'L\'inferenza da screenshot si adatta, ma è costosa', hi:'स्क्रीनशॉट इन्फरेन्स समायोजित होता है, पर महंगा' },
  'compare.r.update.d': { en:'AI detects mismatch, finds new selector, self-heals muscle', zh:'AI 检测到不匹配,找新选择器,自动修复肌肉', ja:'AIが不一致を検出、新セレクタを見つけ、マッスルを自動修復', ko:'AI가 불일치를 감지하고 새 셀렉터를 찾아 근육을 자동 복구', es:'La IA detecta el desajuste, halla un nuevo selector y repara el músculo', fr:'L\'IA détecte l\'écart, trouve un nouveau sélecteur, auto-répare le muscle', de:'KI erkennt die Abweichung, findet einen neuen Selektor, heilt den Muskel selbst', pt:'A IA detecta a divergência, acha novo seletor e repara o músculo', ru:'ИИ замечает расхождение, находит новый селектор, сам чинит мускул', ar:'الذكاء الاصطناعي يكتشف الاختلاف ويجد محددًا جديدًا ويصلح العضلة ذاتيًا', it:'L\'IA rileva la discrepanza, trova un nuovo selettore e auto-ripara il muscolo', hi:'AI बेमेल का पता लगाता है, नया सिलेक्टर खोजता है, मसल को खुद ठीक करता है' },

  'compare.r.privacy.a':{ en:'Local ✅', zh:'本地 ✅', ja:'ローカル ✅', ko:'로컬 ✅', es:'Local ✅', fr:'Local ✅', de:'Lokal ✅', pt:'Local ✅', ru:'Локально ✅', ar:'محلي ✅', it:'Locale ✅', hi:'लोकल ✅' },
  'compare.r.privacy.b':{ en:'Through third-party servers ❌', zh:'经过第三方服务器 ❌', ja:'サードパーティサーバー経由 ❌', ko:'타사 서버 경유 ❌', es:'A través de servidores de terceros ❌', fr:'Via des serveurs tiers ❌', de:'Über Drittanbieter-Server ❌', pt:'Via servidores de terceiros ❌', ru:'Через сторонние серверы ❌', ar:'عبر خوادم طرف ثالث ❌', it:'Tramite server di terze parti ❌', hi:'तीसरे पक्ष के सर्वर के ज़रिए ❌' },
  'compare.r.privacy.c':{ en:'Local ✅', zh:'本地 ✅', ja:'ローカル ✅', ko:'로컬 ✅', es:'Local ✅', fr:'Local ✅', de:'Lokal ✅', pt:'Local ✅', ru:'Локально ✅', ar:'محلي ✅', it:'Locale ✅', hi:'लोकल ✅' },
  'compare.r.privacy.d':{ en:'100% local — 127.0.0.1 only ✅', zh:'100% 本地——仅 127.0.0.1 ✅', ja:'100%ローカル——127.0.0.1のみ ✅', ko:'100% 로컬——127.0.0.1 전용 ✅', es:'100% local — solo 127.0.0.1 ✅', fr:'100% local — 127.0.0.1 uniquement ✅', de:'100% lokal — nur 127.0.0.1 ✅', pt:'100% local — apenas 127.0.0.1 ✅', ru:'100% локально — только 127.0.0.1 ✅', ar:'100% محلي — 127.0.0.1 فقط ✅', it:'100% locale — solo 127.0.0.1 ✅', hi:'100% लोकल——केवल 127.0.0.1 ✅' },

  'compare.r.choice.a': { en:'Any (pure script)', zh:'任意(纯脚本)', ja:'なんでも(純粋なスクリプト)', ko:'무엇이든 (순수 스크립트)', es:'Cualquiera (script puro)', fr:'N\'importe quoi (script pur)', de:'Beliebig (reines Skript)', pt:'Qualquer (script puro)', ru:'Любой (чистый скрипт)', ar:'أي شيء (سكربت خالص)', it:'Qualsiasi (script puro)', hi:'कोई भी (सिर्फ स्क्रिप्ट)' },
  'compare.r.choice.b': { en:'Varies by platform', zh:'因平台而异', ja:'プラットフォーム次第', ko:'플랫폼에 따라 다름', es:'Varía según plataforma', fr:'Varie selon la plateforme', de:'Je nach Plattform', pt:'Varia por plataforma', ru:'Зависит от платформы', ar:'يختلف حسب المنصة', it:'Varia in base alla piattaforma', hi:'प्लेटफ़ॉर्म के अनुसार अलग-अलग' },
  'compare.r.choice.c': { en:'Bundled with Codex / Claude', zh:'与 Codex / Claude 捆绑', ja:'Codex / Claudeにバンドル', ko:'Codex / Claude에 번들', es:'Empaquetado con Codex / Claude', fr:'Inclus avec Codex / Claude', de:'Gebündelt mit Codex / Claude', pt:'Incluído com Codex / Claude', ru:'В комплекте с Codex / Claude', ar:'مدمج مع Codex / Claude', it:'In bundle con Codex / Claude', hi:'Codex / Claude के साथ बंडल' },
  'compare.r.choice.d': { en:'Any AI that speaks HTTP', zh:'任何会说 HTTP 的 AI', ja:'HTTPを話せるAIなら何でも', ko:'HTTP를 말할 수 있는 모든 AI', es:'Cualquier IA que hable HTTP', fr:'N\'importe quelle IA qui parle HTTP', de:'Jede KI, die HTTP spricht', pt:'Qualquer IA que fale HTTP', ru:'Любой ИИ, говорящий по HTTP', ar:'أي ذكاء اصطناعي يفهم HTTP', it:'Qualsiasi IA che parli HTTP', hi:'कोई भी AI जो HTTP बोलता हो' },

  'compare.r.shared.a': { en:'Script = locked to one AI', zh:'脚本 = 绑死一个 AI', ja:'スクリプト = 1つのAIに固定', ko:'스크립트 = 하나의 AI에 고정', es:'Script = atado a una sola IA', fr:'Script = verrouillé à une seule IA', de:'Skript = an eine KI gebunden', pt:'Script = preso a uma IA', ru:'Скрипт = привязан к одному ИИ', ar:'السكربت = مقيّد بذكاء اصطناعي واحد', it:'Script = legato a una sola IA', hi:'स्क्रिप्ट = एक AI से बंधी' },
  'compare.r.shared.b': { en:'Workflow = locked to platform', zh:'工作流 = 绑死平台', ja:'ワークフロー = プラットフォームに固定', ko:'워크플로우 = 플랫폼에 고정', es:'Flujo = atado a la plataforma', fr:'Workflow = verrouillé à la plateforme', de:'Workflow = an Plattform gebunden', pt:'Workflow = preso à plataforma', ru:'Сценарий = привязан к платформе', ar:'سير العمل = مقيّد بالمنصة', it:'Workflow = legato alla piattaforma', hi:'वर्कफ़्लो = प्लेटफ़ॉर्म से बंधी' },
  'compare.r.shared.c': { en:'No persistent memory', zh:'无持久记忆', ja:'永続的な記憶なし', ko:'영구 기억 없음', es:'Sin memoria persistente', fr:'Pas de mémoire persistante', de:'Kein dauerhaftes Gedächtnis', pt:'Sem memória persistente', ru:'Без постоянной памяти', ar:'لا ذاكرة دائمة', it:'Nessuna memoria persistente', hi:'कोई स्थायी मेमोरी नहीं' },
  'compare.r.shared.d': { en:'Muscle files = cross-AI, transferable, permanent', zh:'肌肉文件 = 跨 AI、可迁移、永久', ja:'マッスルファイル = AI間共通、転送可能、永続', ko:'근육 파일 = AI 간 이동 가능, 영구적', es:'Archivos de músculos = cross-IA, transferibles, permanentes', fr:'Fichiers muscles = multi-IA, transférables, permanents', de:'Muskeldateien = KI-übergreifend, übertragbar, dauerhaft', pt:'Arquivos de músculos = cross-IA, transferíveis, permanentes', ru:'Файлы мускулов = между ИИ, переносимы, навсегда', ar:'ملفات العضلات = مشتركة بين النماذج، قابلة للنقل، دائمة', it:'File muscoli = cross-IA, trasferibili, permanenti', hi:'मसल फाइलें = क्रॉस-AI, ट्रांसफरेबल, स्थायी' },

  'compare.caption':    { en:'Muscle memory is cross-AI: knowledge explored by Claude Code today is reused by Codex tomorrow — same JSON files, same Desktop folder.', zh:'肌肉记忆跨 AI 通用:今天 Claude Code 探索出来的知识,明天 Codex 直接复用——同一组 JSON 文件,同一个桌面文件夹。', ja:'マッスルメモリはAI横断:今日Claude Codeが探索した知識を、明日Codexが再利用——同じJSONファイル、同じデスクトップフォルダ。', ko:'근육 기억은 AI를 넘나듭니다: 오늘 Claude Code가 탐색한 지식을 내일 Codex가 그대로 재사용——같은 JSON 파일, 같은 Desktop 폴더.', es:'La memoria muscular es cross-IA: el conocimiento explorado hoy por Claude Code lo reutiliza mañana Codex — mismos archivos JSON, misma carpeta de Escritorio.', fr:'La mémoire musculaire est multi-IA : le savoir exploré par Claude Code aujourd\'hui est réutilisé par Codex demain — mêmes fichiers JSON, même dossier Bureau.', de:'Muskelgedächtnis ist KI-übergreifend: Wissen, das Claude Code heute erkundet, nutzt Codex morgen — gleiche JSON-Dateien, gleicher Desktop-Ordner.', pt:'A memória muscular é cross-IA: o conhecimento explorado hoje por Claude Code é reutilizado amanhã por Codex — mesmos arquivos JSON, mesma pasta Desktop.', ru:'Мускульная память общая для разных ИИ: знания, исследованные Claude Code сегодня, завтра используются Codex — те же JSON-файлы, та же папка на рабочем столе.', ar:'الذاكرة العضلية مشتركة بين الذكاءات الاصطناعية: المعرفة التي يستكشفها Claude Code اليوم يعيد Codex استخدامها غدًا — نفس ملفات JSON، ونفس مجلد سطح المكتب.', it:'La muscle memory è cross-IA: la conoscenza esplorata oggi da Claude Code viene riutilizzata domani da Codex — stessi file JSON, stessa cartella Desktop.', hi:'मसल मेमोरी क्रॉस-AI है: आज Claude Code जो सीखता है, कल Codex उसे फिर से इस्तेमाल करता है——वही JSON फाइलें, वही Desktop फोल्डर।' },

  'compare.heading':    { en:'Why Not Just Use X?', zh:'为什么不直接用 X？', ja:'X を使えばいいのでは？', ko:'그냥 X를 쓰면 안 되나요?', es:'¿Por qué no simplemente usar X?', fr:'Pourquoi ne pas juste utiliser X ?', de:'Warum nicht einfach X nutzen?', pt:'Por que não usar X?', ru:'Почему просто не использовать X?', ar:'لماذا لا نستخدم X فحسب؟', it:'Perché non usare direttamente X?', hi:'सीधे X क्यों न इस्तेमाल करें?' },
  'compare.intro':      { en:'Every existing approach to browser automation has a real cost. Here\'s the honest comparison:', zh:'每一种现有的浏览器自动化方案都有真实的代价。这是诚实的对比:', ja:'既存のブラウザ自動化アプローチにはすべてコストがあります。正直な比較はこちらです:', ko:'기존의 모든 브라우저 자동화 방식에는 실제 비용이 있습니다. 정직한 비교입니다:', es:'Cada enfoque existente de automatización del navegador tiene un coste real. Aquí la comparación honesta:', fr:'Chaque approche existante d\'automatisation du navigateur a un coût réel. Voici la comparaison honnête :', de:'Jeder bestehende Ansatz zur Browser-Automatisierung hat reale Kosten. Hier der ehrliche Vergleich:', pt:'Toda abordagem existente de automação de navegador tem um custo real. Aqui a comparação honesta:', ru:'У каждого существующего подхода к автоматизации браузера есть реальная цена. Вот честное сравнение:', ar:'لكل نهج حالي لأتمتة المتصفح تكلفته الحقيقية. إليك المقارنة الصريحة:', it:'Ogni approccio esistente all\'automazione del browser ha un costo reale. Ecco il confronto onesto:', hi:'ब्राउज़र ऑटोमेशन के हर मौजूदा तरीके की एक वास्तविक कीमत है। यहाँ ईमानदार तुलना है:' },

  // ── Footer ──
  'footer.tagline':   { en:'Give your AI a browser arm.\nMinimal tools, maximum leverage.', zh:'赋予你的 AI 一条浏览器机械臂。\n最少工具，最大杠杆。', ja:'AIにブラウザアームを。\n最小限のツール、最大のレバレッジ。', ko:'AI에게 브라우저 팔을.\n최소 도구, 최대 레버리지.', es:'Dale a tu IA un brazo de navegador.\nHerramientas mínimas, máximo apalancamiento.', fr:'Donnez à votre IA un bras de navigateur.\nOutils minimaux, effet de levier maximal.', de:'Gib deiner KI einen Browser-Arm.\nMinimale Tools, maximale Hebelwirkung.', pt:'Dê ao seu IA um braço de navegador.\nFerramentas mínimas, alavancagem máxima.', ru:'Дайте вашему ИИ руку браузера.\nМинимум инструментов, максимум рычага.', ar:'امنح ذكاءك الاصطناعي ذراع متصفح.\nأدوات بسيطة، أقصى فعالية.', it:'Dai alla tua IA un braccio del browser.\nStrumenti minimali, massima leva.', hi:'अपने AI को ब्राउज़र आर्म दें।\nन्यूनतम उपकरण, अधिकतम लीवरेज।' },
  'footer.product':   { en:'Product', zh:'产品', ja:'プロダクト', ko:'제품', es:'Producto', fr:'Produit', de:'Produkt', pt:'Produto', ru:'Продукт', ar:'المنتج', it:'Prodotto', hi:'उत्पाद' },
  'footer.resources': { en:'Resources', zh:'资源', ja:'リソース', ko:'리소스', es:'Recursos', fr:'Ressources', de:'Ressourcen', pt:'Recursos', ru:'Ресурсы', ar:'الموارد', it:'Risorse', hi:'संसाधन' },
  'footer.legal':     { en:'Legal', zh:'法律', ja:'法的情報', ko:'법적 정보', es:'Legal', fr:'Juridique', de:'Rechtliches', pt:'Legal', ru:'Правовая информация', ar:'قانوني', it:'Legale', hi:'कानूनी' },
  'footer.products':  { en:'Our Products', zh:'我们的产品', ja:'製品一覧', ko:'우리의 제품', es:'Nuestros Productos', fr:'Nos Produits', de:'Unsere Produkte', pt:'Nossos Produtos', ru:'Наши продукты', ar:'منتجاتنا', it:'I Nostri Prodotti', hi:'हमारे उत्पाद' },
  'footer.copy':      { en:'Licensed under BSL 1.1 — free for personal use.', zh:'基于 BSL 1.1 许可 — 个人使用免费。', ja:'BSL 1.1ライセンス — 個人利用無料。', ko:'BSL 1.1 라이선스 — 개인 사용 무료.', es:'Licencia BSL 1.1 — gratis para uso personal.', fr:'Licence BSL 1.1 — gratuit pour usage personnel.', de:'BSL 1.1 Lizenz — kostenlos für Privatnutzung.', pt:'Licença BSL 1.1 — grátis para uso pessoal.', ru:'Лицензия BSL 1.1 — бесплатно для личного использования.', ar:'مرخص بموجب BSL 1.1 — مجاني للاستخدام الشخصي.', it:'Licenza BSL 1.1 — gratuito per uso personale.', hi:'BSL 1.1 लाइसेंस — व्यक्तिगत उपयोग के लिए मुफ़्त।' },
};

const SUPPORTED = LANGS.map(l => l.code);

function detectLang() {
  // 1. User explicitly set a language before
  const saved = localStorage.getItem('lang');
  if (saved && SUPPORTED.includes(saved)) return saved;
  // 2. Auto-detect from browser language
  const browserLang = (navigator.language || '').toLowerCase();
  // Exact match: "zh-cn" → "zh", "ja" → "ja"
  for (const code of SUPPORTED) {
    if (browserLang === code || browserLang.startsWith(code + '-')) return code;
  }
  // Fallback
  return 'en';
}

let currentLang = detectLang();

export function t(key) {
  const entry = T[key];
  if (!entry) return key;
  return entry[currentLang] || entry.en || key;
}

export function getLang() { return currentLang; }

export function setLang(code) {
  currentLang = code;
  localStorage.setItem('lang', code);
  applyAll();
}

/** Pick localized value from a data object: { en:'...', zh:'...', ... } */
export function pick(obj) {
  if (!obj || typeof obj === 'string') return obj || '';
  return obj[currentLang] || obj.en || '';
}

export function applyAll() {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    const val = t(key);
    if (val !== key) el.textContent = val;
  });
  // RTL support for Arabic
  document.documentElement.dir = currentLang === 'ar' ? 'rtl' : 'ltr';
  document.documentElement.lang = currentLang;
}
